"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

export type Locale = "en" | "fr" | "ar";

type LanguageContextType = {
  locale: Locale;
  setLocale: (l: Locale) => void;
  dir: "ltr" | "rtl";
  t: (key: string, vars?: Record<string, string | number>) => string;
};

const translations: Record<Locale, Record<string, string>> = {
  en: {
    "nav.features": "Features",
    "nav.pricing": "Pricing",
    "nav.about": "About",
    "nav.signin": "Sign in",
    "nav.start": "Start free trial",
    "hero.badge": "Made for Moroccan schools",
    "hero.title": "Replace paper — Empower your school",
    "hero.subtitle":
      "EduWave is the all-in-one platform for private school directors and teachers to manage attendance, grades, and behavior — from any device.",
    "hero.cta": "Start 15-Day Free Trial",
    "hero.secondary": "See how it works",
    "hero.note": "No credit card required • Cancel anytime",
    "features.title": "Built for the way Moroccan schools work",
    "features.subtitle": "Everything you need to run a modern school, designed mobile-first.",
    "feat.attendance.title": "Real-time attendance",
    "feat.attendance.desc": "Mark attendance in seconds from any device. Directors see the whole school at a glance.",
    "feat.grades.title": "Smart gradebook",
    "feat.grades.desc": "Configurable periods, coefficients, and auto-calculated averages. Students see results instantly.",
    "feat.behavior.title": "Behavior tracking",
    "feat.behavior.desc": "Capture daily behavior notes that travel with the student across the year.",
    "feat.messaging.title": "Direct messaging",
    "feat.messaging.desc": "Director ↔ Teacher ↔ Student communication in one place, with delivery confirmation.",
    "feat.import.title": "PDF bulk import",
    "feat.import.desc": "Upload a class list PDF and we extract every student automatically. Done in seconds.",
    "feat.multilang.title": "Arabic, French, English",
    "feat.multilang.desc": "Full RTL support and persistent language preferences for every user.",
    "pricing.title": "Simple, fair pricing",
    "pricing.subtitle": "Start free for 15 days. No credit card required.",
    "pricing.monthly": "Monthly",
    "pricing.annual": "Annual",
    "pricing.save": "Save 50%",
    "pricing.cta": "Start 15-day free trial",
    "pricing.choose": "Choose",
    "pricing.perMonth": "/month",
    "pricing.perYear": "/year",
    "pricing.mostPopular": "Most popular",
    "feat.list.1": "Unlimited teachers & students",
    "feat.list.2": "PDF bulk import",
    "feat.list.3": "Direct messaging",
    "feat.list.4": "Mobile & desktop access",
    "feat.list.5": "Priority support",
    "footer.tagline": "Built with care for Moroccan private schools.",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.copyright": "© 2026 EduWave. All rights reserved.",
    "common.signin": "Sign in",
    "common.signup": "Sign up",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.password": "Password",
    "common.fullName": "Full name",
    "common.schoolName": "School name",
    "common.uploadLogo": "Upload school logo",
    "common.continue": "Continue",
    "common.back": "Back",
    "common.signinGoogle": "Sign in with Google",
    "common.signupGoogle": "Sign up with Google",
    "common.or": "or",
    "common.newHere": "New here?",
    "common.alreadyAccount": "Already have an account?",
    "auth.welcomeBack": "Welcome back",
    "auth.welcomeBackSub": "Sign in to your EduWave account",
    "auth.createAccount": "Create your school account",
    "auth.createAccountSub": "Set up your school in less than 2 minutes",
    "auth.welcomeDirector": "Director",
    "auth.welcomeTeacher": "Teacher",
    "auth.welcomeAdmin": "Admin",
    "auth.welcomeStudent": "Student",
    "auth.welcomeParent": "Parent",
    "dashboard.overview": "Overview",
    "dashboard.teachers": "Teachers",
    "dashboard.students": "Students",
    "dashboard.messages": "Messages",
    "dashboard.payment": "Payment",
    "dashboard.sections": "Sections",
    "dashboard.grades": "Grades",
    "dashboard.attendance": "Attendance",
    "dashboard.behavior": "Behavior",
    "dashboard.timetable": "Timetable",
    "dashboard.homework": "Homework",
    "dashboard.notifications": "Notifications",
    "dashboard.lessons": "Lessons",
    "dashboard.exams": "Exams",
    "dashboard.reportCard": "Report Card",
    "dashboard.analytics": "Analytics",
    "dashboard.parents": "Parents",
    "common.relation": "Relation",
    "common.dueDate": "Due date",
    "common.subject": "Subject",
    "common.room": "Room",
    "common.day": "Day",
    "common.time": "Time",
    "common.feedback": "Feedback",
    "common.submit": "Submit",
    "common.score": "Score",
    "common.maxScore": "Max score",
    "common.remarks": "Remarks",
    "common.download": "Download",
    "common.upload": "Upload",
    "common.gradedAt": "Graded at",
    "dashboard.admin": "Admin",
    "common.search": "Search",
    "common.add": "Add",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.send": "Send",
    "common.loading": "Loading...",
    "common.empty": "Nothing here yet",
    "common.theme.light": "Light",
    "common.theme.dark": "Dark",
    "common.language": "Language",
    "common.signout": "Sign out",
    "common.profile": "Profile",
    "trial.daysLeft": "Free trial • {count} day(s) left",
    "trial.upgrade": "Upgrade now",
    "trial.upgradeCta": "Upgrade to keep using EduWave →",
    "stat.teachers": "Teachers",
    "stat.students": "Students",
    "stat.sections": "Sections",
    "stat.todayPresent": "Today present",
    "attendance.title": "Teacher attendance — today",
    "attendance.manageTeachers": "Manage teachers →",
    "attendance.present": "Present",
    "attendance.absent": "Absent",
    "attendance.notMarked": "Not marked",
    "status.PRESENT": "Present",
    "status.ABSENT": "Absent",
    "status.UNKNOWN": "Not marked",
    "director.welcomeBack": "Welcome back, {name}. Here's what's happening today.",
    "director.quickAction": "Quick action",
    "director.addTeacher": "Add a teacher",
    "director.addTeacherDesc": "Auto-generate email + password to share.",
    "director.browseStudents": "Browse students",
    "director.browseStudentsDesc": "View grades, attendance, and behavior.",
    "director.noTeachers": "No teachers yet — add one to get started.",
    "director.clearFilter": "Clear filter",
    "director.teacherCount": "{count} teacher(s)",
    "director.noTeachersWithStatus": "No teachers with status \"{status}\"",
    "msg.title": "Messages",
    "msg.subtitle": "Communicate with your team and students.",
    "msg.newMessage": "New message",
    "msg.sendTo": "Send to",
    "msg.recipient": "Recipient",
    "msg.message": "Message",
    "msg.placeholder": "Type your message…",
    "msg.choose": "Choose…",
    "msg.allTeachers": "All teachers",
    "msg.allStudents": "All students",
    "msg.oneTeacher": "One teacher",
    "msg.oneStudent": "One student",
    "msg.inbox": "Inbox",
    "msg.empty": "No messages yet",
    "msg.you": "You",
    "msg.to": "To",
    "payment.currentPlan": "Current Plan",
    "payment.manageSub": "Manage your subscription and view payment history.",
    "payment.chooseMethod": "Choose Payment Method",
    "payment.selectMethod": "Select how you'd like to pay for your {plan} plan.",
    "payment.payInstantly": "Pay instantly with your credit or debit card",
    "payment.secure": "Secure & encrypted",
    "payment.bankTransfer": "Bank Transfer",
    "payment.bankTransferDesc": "Transfer directly from your bank account",
    "payment.processingTime": "2-3 business days",
    "payment.backToPlans": "Back to plans",
    "payment.backToMethods": "Back to methods",
    "payment.cardDetails": "Card Details",
    "payment.cardholderName": "Cardholder Name",
    "payment.cardNumber": "Card Number",
    "payment.expiry": "Expiry",
    "payment.cvv": "CVV",
    "payment.cardSecure": "Your card information is encrypted and secure",
    "payment.pay": "Pay {amount}",
    "payment.transferTo": "Transfer to",
    "payment.bank": "Bank",
    "payment.amount": "Amount",
    "payment.reference": "Reference",
    "payment.transferNote": "Please include the reference in your transfer so we can match your payment. Your subscription will be activated once the payment is received (2-3 business days).",
    "payment.confirmOrder": "Confirm Order",
    "payment.success": "Payment Successful!",
    "payment.successTransfer": "Order Confirmed!",
    "payment.successMsg": "Your {plan} plan is now active.",
    "payment.successTransferMsg": "We'll send you an email with bank transfer details. Your subscription will activate once payment is received.",
    "payment.done": "Done",
    "payment.history": "Payment History",
    "payment.noPayments": "No payments yet.",
    "payment.alreadyOnPlan": "You are already on this plan!",
    "analytics.title": "Analytics",
    "analytics.subtitle": "School performance analytics and insights.",
    "analytics.attendanceRate": "ATTENDANCE RATE (30 DAYS)",
    "analytics.gradeDistribution": "Grade distribution",
    "analytics.studentsPerSection": "Students per section",
    "analytics.topStudents": "Top 5 performing students",
    "analytics.avgGrades": "Average grades per subject",
    "analytics.noData": "No data yet",
    "analytics.noGrades": "No grades yet",
    "analytics.noSections": "No sections",
    "timetable.manageSlots": "Manage all timetable slots.",
    "timetable.allDays": "All days",
    "timetable.allTeachers": "All teachers",
    "timetable.allSections": "All sections",
    "timetable.noSlots": "No timetable slots found",
    "timetable.selectTeacher": "Select teacher",
    "timetable.selectSection": "Select section",
    "timetable.subjectPlaceholder": "e.g. Math",
    "timetable.roomPlaceholder": "e.g. Room 101",
    "notifications.allCaughtUp": "All caught up",
    "notifications.noNotifications": "No notifications yet",
    "notifications.markAllRead": "Mark all read",
    "notifications.viewAll": "View all",
    "parents.addParent": "Add Parent",
    "parents.addParentDesc": "Create a parent account and link to students.",
    "parents.fullName": "Full name",
    "parents.emailOptional": "Email (optional)",
    "parents.phoneOptional": "Phone (optional)",
    "parents.role": "Parent",
    "parents.linkToStudents": "Link to students",
    "parents.noStudents": "No students yet",
    "parents.createAccount": "Create Parent Account",
    "parents.manageDesc": "Manage parent accounts and link them to students.",
    "parents.noParents": "No parents yet. Click \"Add Parent\" to create one.",
    "parents.accountCreated": "Parent account created!",
    "parents.father": "Father",
    "parents.mother": "Mother",
    "parents.guardian": "Guardian",
    "parents.noSection": "No section"
  },
  fr: {
    "nav.features": "Fonctionnalités",
    "nav.pricing": "Tarifs",
    "nav.about": "À propos",
    "nav.signin": "Se connecter",
    "nav.start": "Essai gratuit",
    "hero.badge": "Conçu pour les écoles marocaines",
    "hero.title": "Remplacez le papier — Donnez vie à votre école",
    "hero.subtitle":
      "EduWave est la plateforme tout-en-un pour les directeurs et enseignants des écoles privées au Maroc : présences, notes, comportement — depuis n'importe quel appareil.",
    "hero.cta": "Démarrer l'essai gratuit de 15 jours",
    "hero.secondary": "Voir comment ça marche",
    "hero.note": "Sans carte bancaire • Annulable à tout moment",
    "features.title": "Conçu pour les écoles marocaines",
    "features.subtitle": "Tout ce dont vous avez besoin, optimisé mobile.",
    "feat.attendance.title": "Présence en temps réel",
    "feat.attendance.desc": "Saisissez les présences en quelques secondes. Le directeur voit toute l'école d'un coup d'œil.",
    "feat.grades.title": "Carnet de notes intelligent",
    "feat.grades.desc": "Périodes configurables, coefficients, moyennes automatiques. Les élèves voient leurs résultats instantanément.",
    "feat.behavior.title": "Suivi du comportement",
    "feat.behavior.desc": "Notes de comportement quotidiennes qui suivent l'élève toute l'année.",
    "feat.messaging.title": "Messagerie directe",
    "feat.messaging.desc": "Communication Directeur ↔ Enseignant ↔ Élève en un seul endroit, avec confirmation de lecture.",
    "feat.import.title": "Import PDF en masse",
    "feat.import.desc": "Importez une liste de classe en PDF, on extrait chaque élève automatiquement.",
    "feat.multilang.title": "Arabe, Français, Anglais",
    "feat.multilang.desc": "Support RTL complet et préférences linguistiques persistantes pour chaque utilisateur.",
    "pricing.title": "Tarifs simples et justes",
    "pricing.subtitle": "15 jours d'essai gratuit. Sans carte bancaire.",
    "pricing.monthly": "Mensuel",
    "pricing.annual": "Annuel",
    "pricing.save": "Économisez 50%",
    "pricing.cta": "Démarrer l'essai gratuit de 15 jours",
    "pricing.choose": "Choisir",
    "pricing.perMonth": "/mois",
    "pricing.perYear": "/an",
    "pricing.mostPopular": "Le plus populaire",
    "feat.list.1": "Enseignants & élèves illimités",
    "feat.list.2": "Import PDF en masse",
    "feat.list.3": "Messagerie directe",
    "feat.list.4": "Accès mobile & desktop",
    "feat.list.5": "Support prioritaire",
    "footer.tagline": "Conçu avec soin pour les écoles privées marocaines.",
    "footer.contact": "Contact",
    "footer.legal": "Légal",
    "footer.privacy": "Confidentialité",
    "footer.terms": "Conditions",
    "footer.copyright": "© 2026 EduWave. Tous droits réservés.",
    "common.signin": "Se connecter",
    "common.signup": "S'inscrire",
    "common.email": "Email",
    "common.phone": "Téléphone",
    "common.password": "Mot de passe",
    "common.fullName": "Nom complet",
    "common.schoolName": "Nom de l'école",
    "common.uploadLogo": "Télécharger le logo",
    "common.continue": "Continuer",
    "common.back": "Retour",
    "common.signinGoogle": "Se connecter avec Google",
    "common.signupGoogle": "S'inscrire avec Google",
    "common.or": "ou",
    "common.newHere": "Nouveau ici ?",
    "common.alreadyAccount": "Vous avez déjà un compte ?",
    "auth.welcomeBack": "Bon retour",
    "auth.welcomeBackSub": "Connectez-vous à votre compte EduWave",
    "auth.createAccount": "Créer le compte de votre école",
    "auth.createAccountSub": "Configurez votre école en moins de 2 minutes",
    "auth.welcomeDirector": "Directeur",
    "auth.welcomeTeacher": "Enseignant",
    "auth.welcomeAdmin": "Admin",
    "auth.welcomeStudent": "Élève",
    "auth.welcomeParent": "Parent",
    "dashboard.overview": "Aperçu",
    "dashboard.teachers": "Enseignants",
    "dashboard.students": "Élèves",
    "dashboard.messages": "Messages",
    "dashboard.payment": "Paiement",
    "dashboard.sections": "Classes",
    "dashboard.grades": "Notes",
    "dashboard.attendance": "Présence",
    "dashboard.behavior": "Comportement",
    "dashboard.timetable": "Emploi du temps",
    "dashboard.homework": "Devoirs",
    "dashboard.notifications": "Notifications",
    "dashboard.lessons": "Leçons",
    "dashboard.exams": "Examens",
    "dashboard.reportCard": "Bulletin",
    "dashboard.analytics": "Analytiques",
    "dashboard.parents": "Parents",
    "common.relation": "Relation",
    "common.dueDate": "Date limite",
    "common.subject": "Matière",
    "common.room": "Salle",
    "common.day": "Jour",
    "common.time": "Heure",
    "common.feedback": "Commentaire",
    "common.submit": "Soumettre",
    "common.score": "Note",
    "common.maxScore": "Note max",
    "common.remarks": "Remarques",
    "common.download": "Télécharger",
    "common.upload": "Téléverser",
    "common.gradedAt": "Noté le",
    "dashboard.admin": "Admin",
    "common.search": "Rechercher",
    "common.add": "Ajouter",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.send": "Envoyer",
    "common.loading": "Chargement...",
    "common.empty": "Rien ici pour le moment",
    "common.theme.light": "Clair",
    "common.theme.dark": "Sombre",
    "common.language": "Langue",
    "common.signout": "Se déconnecter",
    "common.profile": "Profil",
    "trial.daysLeft": "Essai gratuit • {count} jour(s) restant(s)",
    "trial.upgrade": "Mettre à niveau",
    "trial.upgradeCta": "Passer à une version payante →",
    "stat.teachers": "Enseignants",
    "stat.students": "Élèves",
    "stat.sections": "Classes",
    "stat.todayPresent": "Présents aujourd'hui",
    "attendance.title": "Présence des enseignants — aujourd'hui",
    "attendance.manageTeachers": "Gérer les enseignants →",
    "attendance.present": "Présent",
    "attendance.absent": "Absent",
    "attendance.notMarked": "Non marqué",
    "status.PRESENT": "Présent",
    "status.ABSENT": "Absent",
    "status.UNKNOWN": "Non marqué",
    "director.welcomeBack": "Bon retour, {name}. Voici ce qui se passe aujourd'hui.",
    "director.quickAction": "Action rapide",
    "director.addTeacher": "Ajouter un enseignant",
    "director.addTeacherDesc": "Générer automatiquement email + mot de passe à partager.",
    "director.browseStudents": "Parcourir les élèves",
    "director.browseStudentsDesc": "Voir les notes, la présence et le comportement.",
    "director.noTeachers": "Aucun enseignant encore — ajoutez-en un pour commencer.",
    "director.clearFilter": "Effacer le filtre",
    "director.teacherCount": "{count} enseignant(s)",
    "director.noTeachersWithStatus": "Aucun enseignant avec le statut \"{status}\"",
    "msg.title": "Messages",
    "msg.subtitle": "Communiquez avec votre équipe et vos élèves.",
    "msg.newMessage": "Nouveau message",
    "msg.sendTo": "Envoyer à",
    "msg.recipient": "Destinataire",
    "msg.message": "Message",
    "msg.placeholder": "Tapez votre message…",
    "msg.choose": "Choisir…",
    "msg.allTeachers": "Tous les enseignants",
    "msg.allStudents": "Tous les élèves",
    "msg.oneTeacher": "Un enseignant",
    "msg.oneStudent": "Un élève",
    "msg.inbox": "Boîte de réception",
    "msg.empty": "Aucun message pour l'instant",
    "msg.you": "Vous",
    "msg.to": "À",
    "payment.currentPlan": "Plan actuel",
    "payment.manageSub": "Gérez votre abonnement et consultez l'historique des paiements.",
    "payment.chooseMethod": "Choisir le mode de paiement",
    "payment.selectMethod": "Sélectionnez comment vous souhaitez payer votre plan {plan}.",
    "payment.payInstantly": "Payez instantanément avec votre carte bancaire",
    "payment.secure": "Sécurisé et crypté",
    "payment.bankTransfer": "Virement bancaire",
    "payment.bankTransferDesc": "Transférez directement depuis votre compte bancaire",
    "payment.processingTime": "2-3 jours ouvrables",
    "payment.backToPlans": "Retour aux plans",
    "payment.backToMethods": "Retour aux modes",
    "payment.cardDetails": "Coordonnées bancaires",
    "payment.cardholderName": "Nom du titulaire",
    "payment.cardNumber": "Numéro de carte",
    "payment.expiry": "Expiration",
    "payment.cvv": "CVV",
    "payment.cardSecure": "Vos données bancaires sont cryptées et sécurisées",
    "payment.pay": "Payer {amount}",
    "payment.transferTo": "Virement vers",
    "payment.bank": "Banque",
    "payment.amount": "Montant",
    "payment.reference": "Référence",
    "payment.transferNote": "Veuillez inclure la référence dans votre virement pour que nous puissions identifier votre paiement. Votre abonnement sera activé dès réception du paiement (2-3 jours ouvrables).",
    "payment.confirmOrder": "Confirmer la commande",
    "payment.success": "Paiement réussi !",
    "payment.successTransfer": "Commande confirmée !",
    "payment.successMsg": "Votre plan {plan} est maintenant actif.",
    "payment.successTransferMsg": "Nous vous enverrons un email avec les détails du virement. Votre abonnement sera activé dès réception du paiement.",
    "payment.done": "Terminé",
    "payment.history": "Historique des paiements",
    "payment.noPayments": "Aucun paiement pour l'instant.",
    "payment.alreadyOnPlan": "Vous êtes déjà sur ce plan !",
    "analytics.title": "Analytiques",
    "analytics.subtitle": "Analyses et perspectives de performance scolaire.",
    "analytics.attendanceRate": "TAUX DE PRÉSENCE (30 JOURS)",
    "analytics.gradeDistribution": "Distribution des notes",
    "analytics.studentsPerSection": "Élèves par classe",
    "analytics.topStudents": "Top 5 des meilleurs élèves",
    "analytics.avgGrades": "Notes moyennes par matière",
    "analytics.noData": "Aucune donnée",
    "analytics.noGrades": "Aucune note",
    "analytics.noSections": "Aucune classe",
    "timetable.manageSlots": "Gérer tous les créneaux horaires.",
    "timetable.allDays": "Tous les jours",
    "timetable.allTeachers": "Tous les enseignants",
    "timetable.allSections": "Toutes les classes",
    "timetable.noSlots": "Aucun créneau trouvé",
    "timetable.selectTeacher": "Choisir l'enseignant",
    "timetable.selectSection": "Choisir la classe",
    "timetable.subjectPlaceholder": "ex. Maths",
    "timetable.roomPlaceholder": "ex. Salle 101",
    "notifications.allCaughtUp": "Tout est à jour",
    "notifications.noNotifications": "Aucune notification",
    "notifications.markAllRead": "Tout marquer comme lu",
    "notifications.viewAll": "Voir tout",
    "parents.addParent": "Ajouter un parent",
    "parents.addParentDesc": "Créer un compte parent et lier aux élèves.",
    "parents.fullName": "Nom complet",
    "parents.emailOptional": "Email (optionnel)",
    "parents.phoneOptional": "Téléphone (optionnel)",
    "parents.role": "Parent",
    "parents.linkToStudents": "Lier aux élèves",
    "parents.noStudents": "Aucun élève",
    "parents.createAccount": "Créer le compte parent",
    "parents.manageDesc": "Gérer les comptes parents et les lier aux élèves.",
    "parents.noParents": "Aucun parent. Cliquez sur \"Ajouter un parent\" pour en créer un.",
    "parents.accountCreated": "Compte parent créé !",
    "parents.father": "Père",
    "parents.mother": "Mère",
    "parents.guardian": "Tuteur",
    "parents.noSection": "Aucune classe"
  },
  ar: {
    "nav.features": "الميزات",
    "nav.pricing": "الأسعار",
    "nav.about": "حول",
    "nav.signin": "تسجيل الدخول",
    "nav.start": "ابدأ مجاناً",
    "hero.badge": "مصمم للمدارس المغربية",
    "hero.title": "استبدل الورق — نمّ مدرستك",
    "hero.subtitle":
      "إدوويف هي المنصة الشاملة لمديري المدارس الخاصة والمعلمين في المغرب: الحضور والدرجات والسلوك — من أي جهاز.",
    "hero.cta": "ابدأ تجربتك المجانية لمدة 15 يوماً",
    "hero.secondary": "شاهد كيف يعمل",
    "hero.note": "بدون بطاقة ائتمان • إلغاء في أي وقت",
    "features.title": "مصمم للطريقة التي تعمل بها المدارس المغربية",
    "features.subtitle": "كل ما تحتاجه لإدارة مدرسة حديثة، مصمم للهاتف أولاً.",
    "feat.attendance.title": "حضور في الوقت الفعلي",
    "feat.attendance.desc": "سجّل الحضور في ثوانٍ من أي جهاز. المدير يرى المدرسة كاملة بنظرة واحدة.",
    "feat.grades.title": "دفتر نقاط ذكي",
    "feat.grades.desc": "فترات قابلة للتكوين، معاملات، وحساب تلقائي للمعدلات.",
    "feat.behavior.title": "تتبع السلوك",
    "feat.behavior.desc": "ملاحظات سلوك يومية ترافق الطالب طوال السنة.",
    "feat.messaging.title": "رسائل مباشرة",
    "feat.messaging.desc": "تواصل بين المدير والمعلم والطالب في مكان واحد.",
    "feat.import.title": "استيراد جماعي من PDF",
    "feat.import.desc": "ارفع قائمة الفصل وسنستخرج كل طالب تلقائياً.",
    "feat.multilang.title": "عربية، فرنسية، إنجليزية",
    "feat.multilang.desc": "د كامل للـ RTL وتفضيلات لغة مستمرة لكل مستخدم.",
    "pricing.title": "أسعار بسيطة وعادلة",
    "pricing.subtitle": "15 يوماً تجربة مجانية. بدون بطاقة ائتمان.",
    "pricing.monthly": "شهري",
    "pricing.annual": "سنوي",
    "pricing.save": "وفّر 50%",
    "pricing.cta": "ابدأ تجربتك المجانية لمدة 15 يوماً",
    "pricing.choose": "اختر",
    "pricing.perMonth": "/شهر",
    "pricing.perYear": "/سنة",
    "pricing.mostPopular": "الأكثر شيوعاً",
    "feat.list.1": "معلمون وطلاب غير محدودين",
    "feat.list.2": "استيراد PDF جماعي",
    "feat.list.3": "رسائل مباشرة",
    "feat.list.4": "وصول من الجوال والحاسوب",
    "feat.list.5": "دعم ذو أولوية",
    "footer.tagline": "مصمم بعناية للمدارس الخاصة المغربية.",
    "footer.contact": "اتصل بنا",
    "footer.legal": "قانوني",
    "footer.privacy": "الخصوصية",
    "footer.terms": "الشروط",
    "footer.copyright": "© 2026 إدوويف. جميع الحقوق محفوظة.",
    "common.signin": "تسجيل الدخول",
    "common.signup": "إنشاء حساب",
    "common.email": "البريد الإلكتروني",
    "common.phone": "الهاتف",
    "common.password": "كلمة المرور",
    "common.fullName": "الاسم الكامل",
    "common.schoolName": "اسم المدرسة",
    "common.uploadLogo": "تحميل شعار المدرسة",
    "common.continue": "متابعة",
    "common.back": "رجوع",
    "common.signinGoogle": "تسجيل الدخول بـ Google",
    "common.signupGoogle": "إنشاء حساب بـ Google",
    "common.or": "أو",
    "common.newHere": "جديد هنا؟",
    "common.alreadyAccount": "لديك حساب بالفعل؟",
    "auth.welcomeBack": "مرحباً بعودتك",
    "auth.welcomeBackSub": "سجّل الدخول إلى حسابك في إدوويف",
    "auth.createAccount": "أنشئ حساب مدرستك",
    "auth.createAccountSub": "أنشئ مدرستك في أقل من دقيقتين",
    "auth.welcomeDirector": "مدير",
    "auth.welcomeTeacher": "معلم",
    "auth.welcomeAdmin": "المسؤول",
    "auth.welcomeStudent": "طالب",
    "auth.welcomeParent": "ولي الأمر",
    "dashboard.overview": "نظرة عامة",
    "dashboard.teachers": "المعلمون",
    "dashboard.students": "الطلاب",
    "dashboard.messages": "الرسائل",
    "dashboard.payment": "الدفع",
    "dashboard.sections": "الأقسام",
    "dashboard.grades": "الدرجات",
    "dashboard.attendance": "الحضور",
    "dashboard.behavior": "السلوك",
    "dashboard.timetable": "جدول الحصص",
    "dashboard.homework": "الواجبات",
    "dashboard.notifications": "الإشعارات",
    "dashboard.lessons": "الدروس",
    "dashboard.exams": "الامتحانات",
    "dashboard.reportCard": "كشف النقط",
    "dashboard.analytics": "التحليلات",
    "dashboard.parents": "أولياء الأمور",
    "common.relation": "العلاقة",
    "common.dueDate": "تاريخ التسليم",
    "common.subject": "المادة",
    "common.room": "القاعة",
    "common.day": "اليوم",
    "common.time": "الوقت",
    "common.feedback": "التعليق",
    "common.submit": "تسليم",
    "common.score": "النقطة",
    "common.maxScore": "النقطة القصوى",
    "common.remarks": "ملاحظات",
    "common.download": "تحميل",
    "common.upload": "رفع",
    "common.gradedAt": "تاريخ التصحيح",
    "dashboard.admin": "المسؤول",
    "common.search": "بحث",
    "common.add": "إضافة",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.send": "إرسال",
    "common.loading": "جاري التحميل...",
    "common.empty": "لا يوجد شيء هنا بعد",
    "common.theme.light": "فاتح",
    "common.theme.dark": "داكن",
    "common.language": "اللغة",
    "common.signout": "تسجيل الخروج",
    "common.profile": "الملف الشخصي",
    "trial.daysLeft": "تجربة مجانية • {count} يوم متبقي",
    "trial.upgrade": "ترقية الآن",
    "trial.upgradeCta": "ترقية للاستمرار في استخدام إدوويف →",
    "stat.teachers": "المعلمون",
    "stat.students": "الطلاب",
    "stat.sections": "الأقسام",
    "stat.todayPresent": "الحاضرون اليوم",
    "attendance.title": "حضور المعلمين — اليوم",
    "attendance.manageTeachers": "إدارة المعلمين →",
    "attendance.present": "حاضر",
    "attendance.absent": "غائب",
    "attendance.notMarked": "غير مسجل",
    "status.PRESENT": "حاضر",
    "status.ABSENT": "غائب",
    "status.UNKNOWN": "غير مسجل",
    "director.welcomeBack": "مرحباً بعودتك، {name}. إليك ما يحدث اليوم.",
    "director.quickAction": "إجراء سريع",
    "director.addTeacher": "إضافة معلم",
    "director.addTeacherDesc": "إنشاء تلقائي للبريد الإلكتروني وكلمة المرور للمشاركة.",
    "director.browseStudents": "تصفح الطلاب",
    "director.browseStudentsDesc": "عرض الدرجات والحضور والسلوك.",
    "director.noTeachers": "لا يوجد معلمون بعد — أضف واحداً للبدء.",
    "director.clearFilter": "مسح الفلتر",
    "director.teacherCount": "{count} معلم(ين)",
    "director.noTeachersWithStatus": "لا يوجد معلمون بالحالة \"{status}\"",
    "msg.title": "الرسائل",
    "msg.subtitle": "تواصل مع فريقك وطلابك.",
    "msg.newMessage": "رسالة جديدة",
    "msg.sendTo": "إرسال إلى",
    "msg.recipient": "المستلم",
    "msg.message": "الرسالة",
    "msg.placeholder": "اكتب رسالتك…",
    "msg.choose": "اختر…",
    "msg.allTeachers": "كل المعلمين",
    "msg.allStudents": "كل الطلاب",
    "msg.oneTeacher": "معلم واحد",
    "msg.oneStudent": "طالب واحد",
    "msg.inbox": "الوارد",
    "msg.empty": "لا توجد رسائل بعد",
    "msg.you": "أنت",
    "msg.to": "إلى",
    "payment.currentPlan": "الاشتراك الحالي",
    "payment.manageSub": "أدر اشتراكك وعرض سجل المدفوعات.",
    "payment.chooseMethod": "اختر طريقة الدفع",
    "payment.selectMethod": "اختر كيف تريد الدفع مقابل اشتراك {plan}.",
    "payment.payInstantly": "ادفع فوراً ببطاقتك الائتمانية",
    "payment.secure": "آمن ومشفر",
    "payment.bankTransfer": "تحويل بنكي",
    "payment.bankTransferDesc": "تحويل مباشرة من حسابك البنكي",
    "payment.processingTime": "2-3 أيام عمل",
    "payment.backToPlans": "العودة للباقات",
    "payment.backToMethods": "العودة للطرق",
    "payment.cardDetails": "بيانات البطاقة",
    "payment.cardholderName": "اسم حامل البطاقة",
    "payment.cardNumber": "رقم البطاقة",
    "payment.expiry": "تاريخ الانتهاء",
    "payment.cvv": "CVV",
    "payment.cardSecure": "بيانات بطاقتك مشفرة وآمنة",
    "payment.pay": "ادفع {amount}",
    "payment.transferTo": "تحويل إلى",
    "payment.bank": "البنك",
    "payment.amount": "المبلغ",
    "payment.reference": "المرجع",
    "payment.transferNote": "يرجى إدراج المرجع في التحويل حتى نتمكن من مطابقة الدفع. سيتم تفعيل اشتراكك عند استلام الدفع (2-3 أيام عمل).",
    "payment.confirmOrder": "تأكيد الطلب",
    "payment.success": "تم الدفع بنجاح!",
    "payment.successTransfer": "تم تأكيد الطلب!",
    "payment.successMsg": "اشتراك {plan} الآن نشط.",
    "payment.successTransferMsg": "سنرسل لك بريداً إلكترونياً بتفاصيل التحويل البنكي. سيتم تفعيل اشتراكك عند استلام الدفع.",
    "payment.done": "تم",
    "payment.history": "سجل المدفوعات",
    "payment.noPayments": "لا توجد مدفوعات بعد.",
    "payment.alreadyOnPlan": "أنت بالفعل على هذا الاشتراك!",
    "analytics.title": "التحليلات",
    "analytics.subtitle": "تحليلات وأفكار أداء المدرسة.",
    "analytics.attendanceRate": "معدل الحضور (30 يوم)",
    "analytics.gradeDistribution": "توزيع الدرجات",
    "analytics.studentsPerSection": "الطلاب حسب القسم",
    "analytics.topStudents": "أفضل 5 طلاب أداء",
    "analytics.avgGrades": "متوسط الدرجات حسب المادة",
    "analytics.noData": "لا توجد بيانات بعد",
    "analytics.noGrades": "لا توجد درجات بعد",
    "analytics.noSections": "لا توجد أقسام",
    "timetable.manageSlots": "إدارة جميع الحصص الزمنية.",
    "timetable.allDays": "كل الأيام",
    "timetable.allTeachers": "كل المعلمين",
    "timetable.allSections": "كل الأقسام",
    "timetable.noSlots": "لم يتم العثور على حصص",
    "timetable.selectTeacher": "اختر المعلم",
    "timetable.selectSection": "اختر القسم",
    "timetable.subjectPlaceholder": "مثلا: رياضيات",
    "timetable.roomPlaceholder": "مثلا: قاعة 101",
    "notifications.allCaughtUp": "كل شيء محدّث",
    "notifications.noNotifications": "لا توجد إشعارات بعد",
    "notifications.markAllRead": "تعليم الكل كمقروء",
    "notifications.viewAll": "عرض الكل",
    "parents.addParent": "إضافة ولي أمر",
    "parents.addParentDesc": "إنشاء حساب ولي أمر وربطه بالطلاب.",
    "parents.fullName": "الاسم الكامل",
    "parents.emailOptional": "البريد الإلكتروني (اختياري)",
    "parents.phoneOptional": "الهاتف (اختياري)",
    "parents.role": "ولي أمر",
    "parents.linkToStudents": "ربط بالطلاب",
    "parents.noStudents": "لا يوجد طلاب",
    "parents.createAccount": "إنشاء حساب ولي الأمر",
    "parents.manageDesc": "إدارة حسابات أولياء الأمور وربطها بالطلاب.",
    "parents.noParents": "لا يوجد أولياء أمر بعد. اضغط \"إضافة ولي أمر\" لإنشاء واحد.",
    "parents.accountCreated": "تم إنشاء حساب ولي الأمر!",
    "parents.father": "الأب",
    "parents.mother": "الأم",
    "parents.guardian": "الوصي",
    "parents.noSection": "لا يوجد قسم"
  }
};

const LanguageContext = createContext<LanguageContextType | null>(null);

function getSavedLocale(): Locale {
  if (typeof window === "undefined") return "fr";
  try {
    const saved = localStorage.getItem("locale");
    if (saved && ["en", "fr", "ar"].includes(saved)) return saved as Locale;
  } catch {}
  return "fr";
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("fr");
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    const saved = getSavedLocale();
    setLocaleState(saved);
    document.documentElement.setAttribute("dir", saved === "ar" ? "rtl" : "ltr");
    document.documentElement.setAttribute("lang", saved);
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (!hydrated) return;
    const dir = locale === "ar" ? "rtl" : "ltr";
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", locale);
  }, [locale, hydrated]);

  const setLocale = (l: Locale) => {
    setLocaleState(l);
    try {
      localStorage.setItem("locale", l);
    } catch {}
    const dir = l === "ar" ? "rtl" : "ltr";
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", l);
  };

  const dir = locale === "ar" ? "rtl" : "ltr";
  const t = (key: string, vars?: Record<string, string | number>) => {
    let str = translations[locale]?.[key] ?? translations.fr[key] ?? key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, dir, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
