"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

export type Locale = "en" | "fr" | "ar";

type LanguageContextType = {
  locale: Locale;
  setLocale: (l: Locale) => void;
  dir: "ltr" | "rtl";
  t: (key: string, vars?: Record<string, string | number>) => string;
};

const translations: Record<Locale, Record<string, string>> = {
  en: {
    "nav.features": "Features",
    "nav.pricing": "Pricing",
    "nav.about": "About",
    "nav.signin": "Sign in",
    "nav.start": "Start free trial",
    "hero.badge": "Made for Moroccan schools",
    "hero.title": "Replace paper — Empower your school",
    "hero.subtitle":
      "Safha is the all-in-one platform for private school directors and teachers to manage attendance, grades, and behavior — from any device.",
    "hero.cta": "Start 15-Day Free Trial",
    "hero.secondary": "See how it works",
    "hero.note": "No credit card required • Cancel anytime",
    "features.title": "Built for the way Moroccan schools work",
    "features.subtitle": "Everything you need to run a modern school, designed mobile-first.",
    "feat.attendance.title": "Real-time attendance",
    "feat.attendance.desc": "Mark attendance in seconds from any device. Directors see the whole school at a glance.",
    "feat.grades.title": "Smart gradebook",
    "feat.grades.desc": "Configurable periods, coefficients, and auto-calculated averages. Students see results instantly.",
    "feat.behavior.title": "Behavior tracking",
    "feat.behavior.desc": "Capture daily behavior notes that travel with the student across the year.",
    "feat.messaging.title": "Direct messaging",
    "feat.messaging.desc": "Director ↔ Teacher ↔ Student communication in one place, with delivery confirmation.",
    "feat.import.title": "PDF bulk import",
    "feat.import.desc": "Upload a class list PDF and we extract every student automatically. Done in seconds.",
    "feat.multilang.title": "Arabic, French, English",
    "feat.multilang.desc": "Full RTL support and persistent language preferences for every user.",
    "pricing.title": "Simple, fair pricing",
    "pricing.subtitle": "Start free for 15 days. No credit card required.",
    "pricing.monthly": "Monthly",
    "pricing.annual": "Annual",
    "pricing.save": "Save 50%",
    "pricing.cta": "Start 15-day free trial",
    "pricing.choose": "Choose",
    "pricing.perMonth": "/month",
    "pricing.perYear": "/year",
    "pricing.mostPopular": "Most popular",
    "feat.list.1": "Unlimited teachers & students",
    "feat.list.2": "PDF bulk import",
    "feat.list.3": "Direct messaging",
    "feat.list.4": "Mobile & desktop access",
    "feat.list.5": "Priority support",
    "footer.tagline": "Built with care for Moroccan private schools.",
    "footer.contact": "Contact",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.copyright": "© 2026 Safha. All rights reserved.",
    "common.signin": "Sign in",
    "common.signup": "Sign up",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.password": "Password",
    "common.fullName": "Full name",
    "common.schoolName": "School name",
    "common.description": "Description",
    "common.uploadLogo": "Upload school logo",
    "common.continue": "Continue",
    "common.back": "Back",
    "common.signinGoogle": "Sign in with Google",
    "common.signupGoogle": "Sign up with Google",
    "common.or": "or",
    "common.newHere": "New here?",
    "common.alreadyAccount": "Already have an account?",
    "auth.welcomeBack": "Welcome back",
    "auth.welcomeBackSub": "Sign in to your Safha account",
    "auth.createAccount": "Create your school account",
    "auth.createAccountSub": "Set up your school in less than 2 minutes",
    "auth.welcomeDirector": "Director",
    "auth.welcomeTeacher": "Teacher",
    "auth.welcomeAdmin": "Admin",
    "auth.welcomeStudent": "Student",
    "auth.welcomeParent": "Parent",
    "auth.verifyEmail": "Check your email",
    "auth.verifyEmailSub": "We sent a verification link to {email}. Click the link to activate your Safha account.",
    "auth.resendEmail": "Resend email",
    "auth.resendSent": "Verification email sent. Please check your inbox.",
    "auth.resendFailed": "Failed to resend. Please try again.",
    "auth.needVerify": "Please verify your email before signing in.",
    "auth.verifying": "Verifying your email...",
    "auth.verifySuccess": "Email verified! Redirecting to your dashboard...",
    "auth.verifyInvalid": "This verification link is invalid.",
    "auth.verifyExpired": "This verification link has expired. Request a new one below.",
    "auth.verifyGoToDashboard": "Go to my dashboard",
    "auth.verifyHint": "A verification link was sent to your email. Check your inbox (and spam folder).",
    "dashboard.overview": "Overview",
    "dashboard.teachers": "Teachers",
    "dashboard.students": "Students",
    "dashboard.messages": "Messages",
    "dashboard.payment": "Payment",
    "dashboard.sections": "Sections",
    "dashboard.grades": "Grades",
    "dashboard.attendance": "Attendance",
    "dashboard.behavior": "Behavior",
    "dashboard.homework": "Homework",
    "dashboard.notifications": "Notifications",
    "dashboard.lessons": "Lessons",
    "dashboard.exams": "Exams",
    "dashboard.reportCard": "Report Card",
    "dashboard.analytics": "Analytics",
    "dashboard.parents": "Parents",
    "common.relation": "Relation",
    "common.dueDate": "Due date",
    "common.subject": "Subject",
    "common.room": "Room",
    "common.day": "Day",
    "common.time": "Time",
    "common.feedback": "Feedback",
    "common.submit": "Submit",
    "common.score": "Score",
    "common.maxScore": "Max score",
    "common.remarks": "Remarks",
    "common.download": "Download",
    "common.upload": "Upload",
    "common.gradedAt": "Graded at",
    "dashboard.admin": "Admin",
    "common.search": "Search",
    "common.add": "Add",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.send": "Send",
    "common.loading": "Loading...",
    "common.empty": "Nothing here yet",
    "common.theme.light": "Light",
    "common.theme.dark": "Dark",
    "common.language": "Language",
    "common.signout": "Sign out",
    "common.profile": "Profile",
    "trial.daysLeft": "Free trial • {count} day(s) left",
    "trial.upgrade": "Upgrade now",
    "trial.upgradeCta": "Upgrade to keep using Safha →",
    "stat.teachers": "Teachers",
    "stat.students": "Students",
    "stat.sections": "Sections",
    "stat.todayPresent": "Today present",
    "attendance.title": "Teacher attendance — today",
    "attendance.manageTeachers": "Manage teachers →",
    "attendance.present": "Present",
    "attendance.absent": "Absent",
    "attendance.notMarked": "Not marked",
    "status.PRESENT": "Present",
    "status.ABSENT": "Absent",
    "status.UNKNOWN": "Not marked",
    "director.welcomeBack": "Welcome back, {name}. Here's what's happening today.",
    "director.quickAction": "Quick action",
    "director.addTeacher": "Add a teacher",
    "director.addTeacherDesc": "Auto-generate email + password to share.",
    "director.browseStudents": "Browse students",
    "director.browseStudentsDesc": "View grades, attendance, and behavior.",
    "director.noTeachers": "No teachers yet — add one to get started.",
    "director.clearFilter": "Clear filter",
    "director.teacherCount": "{count} teacher(s)",
    "director.noTeachersWithStatus": "No teachers with status \"{status}\"",
    "msg.title": "Messages",
    "msg.subtitle": "Communicate with your team and students.",
    "msg.newMessage": "New message",
    "msg.sendTo": "Send to",
    "msg.recipient": "Recipient",
    "msg.message": "Message",
    "msg.placeholder": "Type your message…",
    "msg.choose": "Choose…",
    "msg.allTeachers": "All teachers",
    "msg.allStudents": "All students",
    "msg.oneTeacher": "One teacher",
    "msg.oneStudent": "One student",
    "msg.inbox": "Inbox",
    "msg.empty": "No messages yet",
    "msg.you": "You",
    "msg.to": "To",
    "chat.newChat": "New chat",
    "chat.contacts": "Contacts",
    "chat.selectChat": "Select a conversation to start messaging",
    "chat.noConversations": "No conversations yet",
    "chat.noContacts": "No contacts available",
    "chat.searchPlaceholder": "Search…",
    "chat.typeMessage": "Type a message…",
    "chat.noResults": "No matches found",
    "chat.online": "Online",
    "chat.yesterday": "Yesterday",
    "chat.sent": "Message sent",
    "chat.sendFailed": "Failed to send message",
    "chat.loadFailed": "Failed to load messages",
    "chat.you": "You",
    "chat.startConversation": "Say hello to start the conversation",
    "payment.currentPlan": "Current Plan",
    "payment.manageSub": "Manage your subscription and view payment history.",
    "payment.chooseMethod": "Choose Payment Method",
    "payment.selectMethod": "Select how you'd like to pay for your {plan} plan.",
    "payment.payInstantly": "Pay instantly with your credit or debit card",
    "payment.secure": "Secure & encrypted",
    "payment.bankTransfer": "Bank Transfer",
    "payment.bankTransferDesc": "Transfer directly from your bank account",
    "payment.processingTime": "2-3 business days",
    "payment.backToPlans": "Back to plans",
    "payment.backToMethods": "Back to methods",
    "payment.cardDetails": "Card Details",
    "payment.cardholderName": "Cardholder Name",
    "payment.cardNumber": "Card Number",
    "payment.expiry": "Expiry",
    "payment.cvv": "CVV",
    "payment.cardSecure": "Your card information is encrypted and secure",
    "payment.pay": "Pay {amount}",
    "payment.transferTo": "Transfer to",
    "payment.bank": "Bank",
    "payment.amount": "Amount",
    "payment.reference": "Reference",
    "payment.transferNote": "Please include the reference in your transfer so we can match your payment. Your subscription will be activated once the payment is received (2-3 business days).",
    "payment.confirmOrder": "Confirm Order",
    "payment.success": "Payment Successful!",
    "payment.successTransfer": "Order Confirmed!",
    "payment.successMsg": "Your {plan} plan is now active.",
    "payment.successTransferMsg": "We'll send you an email with bank transfer details. Your subscription will activate once payment is received.",
    "payment.done": "Done",
    "payment.history": "Payment History",
    "payment.noPayments": "No payments yet.",
    "payment.alreadyOnPlan": "You are already on this plan!",
    "analytics.title": "Analytics",
    "analytics.subtitle": "School performance analytics and insights.",
    "analytics.attendanceRate": "ATTENDANCE RATE (30 DAYS)",
    "analytics.gradeDistribution": "Grade distribution",
    "analytics.studentsPerSection": "Students per section",
    "analytics.topStudents": "Top 5 performing students",
    "analytics.avgGrades": "Average grades per subject",
    "analytics.noData": "No data yet",
    "analytics.noGrades": "No grades yet",
    "analytics.noSections": "No sections",
    "notifications.allCaughtUp": "All caught up",
    "notifications.noNotifications": "No notifications yet",
    "notifications.markAllRead": "Mark all read",
    "notifications.viewAll": "View all",
    "parents.addParent": "Add Parent",
    "parents.addParentDesc": "Create a parent account and link to students.",
    "parents.fullName": "Full name",
    "parents.emailOptional": "Email (optional)",
    "parents.phoneOptional": "Phone (optional)",
    "parents.role": "Parent",
    "parents.linkToStudents": "Link to students",
    "parents.noStudents": "No students yet",
    "parents.createAccount": "Create Parent Account",
    "parents.manageDesc": "Manage parent accounts and link them to students.",
    "parents.noParents": "No parents yet. Click \"Add Parent\" to create one.",
    "parents.accountCreated": "Parent account created!",
    "parents.father": "Father",
    "parents.mother": "Mother",
    "parents.guardian": "Guardian",
    "parents.noSection": "No section",
    "common.allSections": "All sections",
    "common.choose": "Choose…",
    "common.student": "Student",
    "common.section": "Section",
    "common.name": "Name",
    "common.date": "Date",
    "common.failed": "Failed",
    "common.retry": "Retry",
    "common.home": "Go to homepage",
    "error.title": "Something went wrong",
    "error.subtitle": "An unexpected error occurred. Please try again.",
    "common.title": "Title",
    "common.content": "Content",
    "common.startTime": "Start time",
    "common.endTime": "End time",
    "teacher.overview.markedStatus": "Marked {status} for today",
    "teacher.overview.myAttendanceToday": "My attendance — today",
    "teacher.overview.presentToday": "Present today",
    "teacher.overview.markPresent": "Mark present",
    "teacher.overview.absentToday": "Absent today",
    "teacher.overview.markAbsent": "Mark absent",
    "teacher.overview.notMarkedYet": "You haven't marked your attendance yet.",
    "teacher.overview.students": "Students",
    "teacher.overview.sections": "Sections",
    "teacher.overview.mySections": "My sections",
    "teacher.overview.studentsCount": "{count} students",
    "teacher.attendance.subtitle": "Mark daily attendance for your students.",
    "teacher.attendance.total": "total",
    "teacher.attendance.noStudents": "No students in your class yet.",
    "teacher.grades.gradeAdded": "Grade added",
    "teacher.grades.subtitle": "Add grades and configure exam periods.",
    "teacher.grades.periods": "Periods",
    "teacher.grades.addGrade": "Add grade",
    "teacher.grades.addGradeTitle": "Add grade",
    "teacher.grades.examPeriods": "Exam periods",
    "teacher.grades.noPeriods": "No periods yet. Click \"Periods\" to add one.",
    "teacher.grades.periodInfo": "×{coefficient} · {examCount} exams",
    "teacher.grades.allGrades": "All grades",
    "teacher.grades.noGrades": "No grades yet.",
    "teacher.grades.noGradesSection": "No grades in this section.",
    "teacher.grades.period": "Period",
    "teacher.grades.max": "Max",
    "teacher.grades.editPeriod": "Edit period",
    "teacher.grades.newExamPeriod": "New exam period",
    "teacher.grades.start": "Start",
    "teacher.grades.end": "End",
    "teacher.grades.coefficient": "Coefficient",
    "teacher.grades.examCount": "Exam count",
    "teacher.grades.create": "Create",
    "teacher.grades.periodUpdated": "Period updated",
    "teacher.grades.periodCreated": "Period created",
    "teacher.grades.deletePeriodConfirm": "Delete period \"{name}\"?",
    "teacher.grades.periodDeleted": "Period deleted",
    "teacher.grades.subjectPlaceholder": "Mathematics",
    "teacher.grades.namePlaceholder": "Semester 1",
    "teacher.exams.examCreated": "Exam created",
    "teacher.exams.deleteExamConfirm": "Delete this exam?",
    "teacher.exams.examDeleted": "Exam deleted",
    "teacher.exams.failedLoadResults": "Failed to load results",
    "teacher.exams.scoreSaved": "Score saved",
    "teacher.exams.failedSaveScore": "Failed to save score",
    "teacher.exams.subtitle": "Create and manage exams.",
    "teacher.exams.addExam": "Add exam",
    "teacher.exams.noExams": "No exams yet. Click \"Add exam\" to create one.",
    "teacher.exams.noStudentsFound": "No students found.",
    "teacher.exams.addExamTitle": "Add exam",
    "teacher.exams.namePlaceholder": "Midterm exam",
    "teacher.exams.coefficient": "Coefficient",
    "teacher.exams.maxScore": "Max score",
    "teacher.homework.subtitle": "Create and manage homework assignments.",
    "teacher.homework.addHomework": "Add Homework",
    "teacher.homework.assignments": "Assignments",
    "teacher.homework.noHomework": "No homework yet. Click \"Add Homework\" to create one.",
    "teacher.homework.noHomeworkSection": "No homework in this section.",
    "teacher.homework.due": "Due",
    "teacher.homework.overdue": "Overdue",
    "teacher.homework.submissionsCount": "{count} submission(s)",
    "teacher.homework.attachedFile": "Attached file",
    "teacher.homework.noSubmissions": "No submissions yet.",
    "teacher.homework.submitted": "Submitted",
    "teacher.homework.attachment": "Attachment",
    "teacher.homework.feedbackPlaceholder": "Feedback...",
    "teacher.homework.update": "Update",
    "teacher.homework.grade": "Grade",
    "teacher.homework.newHomework": "New Homework",
    "teacher.homework.titlePlaceholder": "Chapter 5 Exercises",
    "teacher.homework.descriptionPlaceholder": "Assignment details...",
    "teacher.homework.fileUrlOptional": "File URL (optional)",
    "teacher.homework.create": "Create",
    "teacher.homework.homeworkCreated": "Homework created",
    "teacher.homework.deleteConfirm": "Delete \"{title}\"?",
    "teacher.homework.deleted": "Deleted",
    "teacher.homework.graded": "Graded",
    "teacher.behavior.chooseStudent": "Choose a student",
    "teacher.behavior.noteAdded": "Behavior note added",
    "teacher.behavior.subtitle": "Track behavior notes for your students.",
    "teacher.behavior.note": "note",
    "teacher.behavior.noNotes": "No behavior notes yet.",
    "teacher.behavior.addNoteTitle": "Add behavior note",
    "teacher.behavior.type": "Type",
    "teacher.behavior.positive": "Positive",
    "teacher.behavior.neutral": "Neutral",
    "teacher.behavior.negative": "Negative",
    "teacher.behavior.noteLabel": "Note",
    "teacher.behavior.notePlaceholder": "Describe the behavior…",
    "messages.chooseStudent": "Choose a student",
    "teacher.messages.sent": "Message sent",
    "teacher.messages.sendFailed": "Send failed",
    "teacher.messages.subtitle": "Talk to your director and students.",
    "teacher.messages.newMessage": "New message",
    "teacher.messages.sendTo": "Send to",
    "teacher.messages.director": "Director",
    "teacher.messages.allStudents": "All students",
    "teacher.messages.oneStudent": "One student",
    "teacher.messages.messageLabel": "Message",
    "teacher.messages.placeholder": "Type your message…",
    "teacher.messages.inbox": "Inbox",
    "teacher.lessons.lessonCreated": "Lesson created",
    "teacher.lessons.deleteConfirm": "Delete this lesson?",
    "teacher.lessons.lessonDeleted": "Lesson deleted",
    "teacher.lessons.subtitle": "Create and manage lessons for your sections.",
    "teacher.lessons.addLesson": "Add lesson",
    "teacher.lessons.noLessonsSection": "No lessons in this section.",
    "teacher.lessons.noLessons": "No lessons yet. Click \"Add lesson\" to create one.",
    "teacher.lessons.noContent": "No content.",
    "teacher.lessons.file": "File",
    "teacher.lessons.video": "Video",
    "teacher.lessons.addLessonTitle": "Add lesson",
    "teacher.lessons.titlePlaceholder": "Lesson title",
    "teacher.lessons.contentPlaceholder": "Lesson content…",
    "teacher.lessons.fileUrlOptional": "File URL (optional)",
    "teacher.lessons.videoUrlOptional": "Video URL (optional)",
    "teacher.sections.sectionAdded": "Section added",
    "teacher.sections.deleteConfirm": "Delete section {name}?",
    "teacher.sections.sectionDeleted": "Section deleted",
    "teacher.sections.deleteFailed": "Delete failed",
    "teacher.sections.subtitle": "Manage your classes.",
    "teacher.sections.section": "section",
    "teacher.sections.noSections": "No sections yet.",
    "teacher.sections.studentsCount": "{count} students",
    "teacher.sections.addSectionTitle": "Add section",
    "teacher.sections.sectionName": "Section name",
    "teacher.students.studentAdded": "Student added!",
    "teacher.students.deleteConfirm": "Delete {name}?",
    "teacher.students.studentDeleted": "Student deleted",
    "teacher.students.deleteFailed": "Delete failed",
    "teacher.students.passwordReset": "Password reset",
    "teacher.students.subtitle": "Manage your students.",
    "teacher.students.importPdf": "Import PDF",
    "teacher.students.noStudents": "No students yet.",
    "teacher.students.addStudentTitle": "Add student",
    "teacher.students.firstName": "First name",
    "teacher.students.lastName": "Last name",
    "teacher.students.serialNumber": "Serial #",
    "teacher.students.noSection": "No section",
    "teacher.students.emailPasswordInfo": "An email and password will be generated. Share them with the student to log in.",
    "teacher.students.credentialsTitle": "Student credentials",
    "director.exams.overview": "Overview of all exams across sections.",
    "director.exams.allSections": "All sections",
    "director.exams.total": "Total",
    "director.exams.graded": "Graded",
    "director.exams.pending": "Pending",
    "director.exams.noExamsInSection": "No exams in this section.",
    "director.exams.noExams": "No exams yet.",
    "director.exams.deleteConfirm": "Delete exam \"{name}\"? This cannot be undone.",
    "director.exams.deleteSuccess": "Exam deleted",
    "director.exams.deleteFailed": "Delete failed",
    "director.exams.editTitle": "Edit exam",
    "director.exams.updateSuccess": "Exam updated",
    "director.exams.updateFailed": "Update failed",
    "director.payment.fillAllFields": "Please fill in all card fields",
    "director.payment.failed": "Payment failed",
    "director.payment.freeTrial": "Free Trial",
    "director.payment.active": "ACTIVE",
    "director.payment.card": "card",
    "director.analytics.loadFailed": "Failed to load analytics",
    "director.analytics.noDataAvailable": "No data available",
    "director.analytics.retry": "Retry",
    "director.teachers.couldNotCopy": "Could not copy",
    "director.teachers.addSuccess": "Teacher added. Share the credentials below.",
    "director.teachers.addFailed": "Failed",
    "director.teachers.deleteConfirm": "Delete teacher {name}? This cannot be undone.",
    "director.teachers.deleteSuccess": "Teacher deleted",
    "director.teachers.deleteFailed": "Delete failed",
    "director.teachers.subtitle": "Add teachers and share auto-generated credentials.",
    "director.teachers.addTeacherBtn": "Add teacher",
    "director.teachers.noTeachers": "No teachers yet. Click \"Add teacher\" to get started.",
    "director.teachers.name": "Name",
    "director.teachers.subject": "Subject",
    "director.teachers.email": "Email",
    "director.teachers.password": "Password",
    "director.teachers.students": "Students",
    "director.teachers.actions": "Actions",
    "director.teachers.modalTitleAdd": "Add teacher",
    "director.teachers.modalTitleAdded": "Teacher added",
    "director.teachers.credentialsNote": "has been added. Share these credentials with them — they won't be shown again.",
    "director.teachers.done": "Done",
    "director.teachers.firstName": "First name",
    "director.teachers.lastName": "Last name",
    "director.teachers.subjectLabel": "Subject",
    "director.teachers.autoGenerate": "We'll auto-generate a unique email and 10-character password for this teacher.",
    "director.students.subtitle": "All students across all teachers.",
    "director.students.noStudents": "No students yet.",
    "director.students.unassigned": "Unassigned",
    "director.students.grades": "grades",
    "director.students.present": "present",
    "director.students.absent": "absent",
    "director.students.notes": "notes",
    "director.students.password": "Password:",
    "director.students.viewDetails": "View details",
    "director.students.student": "Student",
    "director.students.avg": "Avg",
    "director.students.presentLabel": "Present",
    "director.students.absentLabel": "Absent",
    "director.students.notesLabel": "Notes",
    "director.students.gradesTitle": "Grades",
    "director.students.behaviorTitle": "Behavior notes",
    "director.students.nothingHere": "Nothing here yet.",
    "director.messages.chooseRecipient": "Please choose a recipient",
    "director.messages.sent": "Message sent",
    "director.messages.sendFailed": "Send failed",
    "director.notifications.loadFailed": "Failed to load notifications",
    "director.notifications.unreadCount": "{count} unread",
    "director.notifications.retry": "Retry",
    "student.overview.welcome": "Welcome, {name} 👋",
    "student.overview.dashboardSubtitle": "Your student dashboard",
    "student.overview.overallAvg": "Overall avg",
    "student.overview.present": "Present",
    "student.overview.grades": "Grades",
    "student.overview.notes": "Notes",
    "student.overview.recentGrades": "Recent grades",
    "student.overview.noGrades": "No grades yet.",
    "student.overview.behaviorNotes": "Behavior notes",
    "student.overview.noBehaviorNotes": "No behavior notes.",
    "student.overview.recentMessages": "Recent messages",
    "student.overview.from": "From",
    "student.overview.retry": "Retry",
    "student.reportCard.retry": "Retry",
    "student.reportCard.title": "Report Card",
    "student.reportCard.subtitle": "Academic performance summary",
    "student.reportCard.downloadPdf": "Download PDF",
    "student.reportCard.emptyState": "No grades recorded yet. Report card will be available once grades are entered.",
    "student.reportCard.student": "Student",
    "student.reportCard.teacher": "Teacher:",
    "student.reportCard.overallAverage": "Overall average",
    "student.reportCard.periodAverage": "Period average",
    "student.reportCard.subject": "Subject",
    "student.reportCard.score": "Score",
    "student.reportCard.grade": "Grade",
    "student.reportCard.excellent": "Excellent",
    "student.reportCard.passing": "Passing",
    "student.reportCard.needsImprovement": "Needs improvement",
    "student.reportCard.weightedAverage": "Weighted average:",
    "student.reportCard.examCount": "exam(s)",
    "student.homework.submitted": "Submitted",
    "student.homework.failed": "Failed",
    "student.homework.subtitle": "View and submit your homework assignments.",
    "student.homework.noHomework": "No homework assigned yet.",
    "student.homework.teacher": "Teacher:",
    "student.homework.due": "Due:",
    "student.homework.section": "Section:",
    "student.homework.attachment": "Attachment",
    "student.homework.submit": "Submit",
    "student.homework.feedback": "Feedback",
    "student.homework.graded": "Graded",
    "student.homework.submittedWaiting": "Submitted — waiting for grading.",
    "student.homework.submitHomework": "Submit Homework",
    "student.homework.yourAnswer": "Your answer",
    "student.homework.answerPlaceholder": "Write your answer here...",
    "student.homework.fileUrlOptional": "File URL (optional)",
    "student.homework.cancel": "Cancel",
    "student.homework.overdue": "Overdue",
    "student.homework.pending": "Pending",
    "student.exams.retry": "Retry",
    "student.exams.title": "Exams",
    "student.exams.subtitle": "Your exam results and grades.",
    "student.exams.noExams": "No exams yet.",
    "student.exams.pending": "Pending",
    "student.exams.graded": "Graded",
    "student.grades.retry": "Retry",
    "student.grades.title": "My grades",
    "student.grades.subtitle": "All your grades and averages.",
    "student.grades.overallAverage": "Overall average",
    "student.grades.noGrades": "No grades yet.",
    "student.grades.average": "Average",
    "student.grades.noGradesPeriod": "No grades in this period.",
    "student.attendance.retry": "Retry",
    "student.attendance.title": "My attendance",
    "student.attendance.subtitle": "Your attendance history.",
    "student.attendance.present": "Present",
    "student.attendance.absent": "Absent",
    "student.attendance.noRecords": "No attendance records yet.",
    "student.behavior.retry": "Retry",
    "student.behavior.title": "Behavior notes",
    "student.behavior.subtitle": "Notes from your teachers.",
    "student.behavior.noNotes": "No behavior notes yet. Keep up the good work!",
    "student.messages.sent": "Message sent to your teachers",
    "student.messages.sendFailed": "Send failed",
    "student.messages.title": "Messages",
    "student.messages.subtitle": "Chat with your teachers and director.",
    "student.messages.newMessage": "New message",
    "student.messages.to": "To",
    "student.messages.allTeachers": "All your teachers",
    "student.messages.message": "Message",
    "student.messages.placeholder": "Type your message…",
    "student.messages.send": "Send",
    "student.messages.conversation": "Conversation",
    "student.messages.retry": "Retry",
    "student.messages.noMessages": "No messages yet",
    "student.messages.you": "You",
    "student.lessons.retry": "Retry",
    "student.lessons.title": "Lessons",
    "student.lessons.subtitle": "Browse lessons for your section.",
    "student.lessons.noLessons": "No lessons available yet.",
    "student.lessons.noContent": "No content.",
    "student.lessons.file": "File",
    "student.lessons.video": "Video",
  },
  fr: {
    "nav.features": "Fonctionnalités",
    "nav.pricing": "Tarifs",
    "nav.about": "À propos",
    "nav.signin": "Se connecter",
    "nav.start": "Essai gratuit",
    "hero.badge": "Conçu pour les écoles marocaines",
    "hero.title": "Remplacez le papier — Donnez vie à votre école",
    "hero.subtitle":
      "Safha est la plateforme tout-en-un pour les directeurs et enseignants des écoles privées au Maroc : présences, notes, comportement — depuis n'importe quel appareil.",
    "hero.cta": "Démarrer l'essai gratuit de 15 jours",
    "hero.secondary": "Voir comment ça marche",
    "hero.note": "Sans carte bancaire • Annulable à tout moment",
    "features.title": "Conçu pour les écoles marocaines",
    "features.subtitle": "Tout ce dont vous avez besoin, optimisé mobile.",
    "feat.attendance.title": "Présence en temps réel",
    "feat.attendance.desc": "Saisissez les présences en quelques secondes. Le directeur voit toute l'école d'un coup d'œil.",
    "feat.grades.title": "Carnet de notes intelligent",
    "feat.grades.desc": "Périodes configurables, coefficients, moyennes automatiques. Les élèves voient leurs résultats instantanément.",
    "feat.behavior.title": "Suivi du comportement",
    "feat.behavior.desc": "Notes de comportement quotidiennes qui suivent l'élève toute l'année.",
    "feat.messaging.title": "Messagerie directe",
    "feat.messaging.desc": "Communication Directeur ↔ Enseignant ↔ Élève en un seul endroit, avec confirmation de lecture.",
    "feat.import.title": "Import PDF en masse",
    "feat.import.desc": "Importez une liste de classe en PDF, on extrait chaque élève automatiquement.",
    "feat.multilang.title": "Arabe, Français, Anglais",
    "feat.multilang.desc": "Support RTL complet et préférences linguistiques persistantes pour chaque utilisateur.",
    "pricing.title": "Tarifs simples et justes",
    "pricing.subtitle": "15 jours d'essai gratuit. Sans carte bancaire.",
    "pricing.monthly": "Mensuel",
    "pricing.annual": "Annuel",
    "pricing.save": "Économisez 50%",
    "pricing.cta": "Démarrer l'essai gratuit de 15 jours",
    "pricing.choose": "Choisir",
    "pricing.perMonth": "/mois",
    "pricing.perYear": "/an",
    "pricing.mostPopular": "Le plus populaire",
    "feat.list.1": "Enseignants & élèves illimités",
    "feat.list.2": "Import PDF en masse",
    "feat.list.3": "Messagerie directe",
    "feat.list.4": "Accès mobile & desktop",
    "feat.list.5": "Support prioritaire",
    "footer.tagline": "Conçu avec soin pour les écoles privées marocaines.",
    "footer.contact": "Contact",
    "footer.legal": "Légal",
    "footer.privacy": "Confidentialité",
    "footer.terms": "Conditions",
    "footer.copyright": "© 2026 Safha. Tous droits réservés.",
    "common.signin": "Se connecter",
    "common.signup": "S'inscrire",
    "common.email": "Email",
    "common.phone": "Téléphone",
    "common.password": "Mot de passe",
    "common.fullName": "Nom complet",
    "common.schoolName": "Nom de l'école",
    "common.description": "Description",
    "common.uploadLogo": "Télécharger le logo",
    "common.continue": "Continuer",
    "common.back": "Retour",
    "common.signinGoogle": "Se connecter avec Google",
    "common.signupGoogle": "S'inscrire avec Google",
    "common.or": "ou",
    "common.newHere": "Nouveau ici ?",
    "common.alreadyAccount": "Vous avez déjà un compte ?",
    "auth.welcomeBack": "Bon retour",
    "auth.welcomeBackSub": "Connectez-vous à votre compte Safha",
    "auth.createAccount": "Créer le compte de votre école",
    "auth.createAccountSub": "Configurez votre école en moins de 2 minutes",
    "auth.welcomeDirector": "Directeur",
    "auth.welcomeTeacher": "Enseignant",
    "auth.welcomeAdmin": "Admin",
    "auth.welcomeStudent": "Élève",
    "auth.welcomeParent": "Parent",
    "auth.verifyEmail": "Vérifiez votre e-mail",
    "auth.verifyEmailSub": "Nous avons envoyé un lien de vérification à {email}. Cliquez sur le lien pour activer votre compte Safha.",
    "auth.resendEmail": "Renvoyer l'e-mail",
    "auth.resendSent": "E-mail de vérification envoyé. Vérifiez votre boîte de réception.",
    "auth.resendFailed": "Échec de l'envoi. Veuillez réessayer.",
    "auth.needVerify": "Veuillez vérifier votre e-mail avant de vous connecter.",
    "auth.verifying": "Vérification de votre e-mail...",
    "auth.verifySuccess": "E-mail vérifié ! Redirection vers votre tableau de bord...",
    "auth.verifyInvalid": "Ce lien de vérification est invalide.",
    "auth.verifyExpired": "Ce lien de vérification a expiré. Demandez-en un nouveau ci-dessous.",
    "auth.verifyGoToDashboard": "Aller à mon tableau de bord",
    "auth.verifyHint": "Un lien de vérification a été envoyé à votre e-mail. Vérifiez votre boîte de réception (et vos spams).",
    "dashboard.overview": "Aperçu",
    "dashboard.teachers": "Enseignants",
    "dashboard.students": "Élèves",
    "dashboard.messages": "Messages",
    "dashboard.payment": "Paiement",
    "dashboard.sections": "Classes",
    "dashboard.grades": "Notes",
    "dashboard.attendance": "Présence",
    "dashboard.behavior": "Comportement",
    "dashboard.homework": "Devoirs",
    "dashboard.notifications": "Notifications",
    "dashboard.lessons": "Leçons",
    "dashboard.exams": "Examens",
    "dashboard.reportCard": "Bulletin",
    "dashboard.analytics": "Analytiques",
    "dashboard.parents": "Parents",
    "common.relation": "Relation",
    "common.dueDate": "Date limite",
    "common.subject": "Matière",
    "common.room": "Salle",
    "common.day": "Jour",
    "common.time": "Heure",
    "common.feedback": "Commentaire",
    "common.submit": "Soumettre",
    "common.score": "Note",
    "common.maxScore": "Note max",
    "common.remarks": "Remarques",
    "common.download": "Télécharger",
    "common.upload": "Téléverser",
    "common.gradedAt": "Noté le",
    "dashboard.admin": "Admin",
    "common.search": "Rechercher",
    "common.add": "Ajouter",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.save": "Enregistrer",
    "common.cancel": "Annuler",
    "common.send": "Envoyer",
    "common.loading": "Chargement...",
    "common.empty": "Rien ici pour le moment",
    "common.theme.light": "Clair",
    "common.theme.dark": "Sombre",
    "common.language": "Langue",
    "common.signout": "Se déconnecter",
    "common.profile": "Profil",
    "trial.daysLeft": "Essai gratuit • {count} jour(s) restant(s)",
    "trial.upgrade": "Mettre à niveau",
    "trial.upgradeCta": "Passer à une version payante →",
    "stat.teachers": "Enseignants",
    "stat.students": "Élèves",
    "stat.sections": "Classes",
    "stat.todayPresent": "Présents aujourd'hui",
    "attendance.title": "Présence des enseignants — aujourd'hui",
    "attendance.manageTeachers": "Gérer les enseignants →",
    "attendance.present": "Présent",
    "attendance.absent": "Absent",
    "attendance.notMarked": "Non marqué",
    "status.PRESENT": "Présent",
    "status.ABSENT": "Absent",
    "status.UNKNOWN": "Non marqué",
    "director.welcomeBack": "Bon retour, {name}. Voici ce qui se passe aujourd'hui.",
    "director.quickAction": "Action rapide",
    "director.addTeacher": "Ajouter un enseignant",
    "director.addTeacherDesc": "Générer automatiquement email + mot de passe à partager.",
    "director.browseStudents": "Parcourir les élèves",
    "director.browseStudentsDesc": "Voir les notes, la présence et le comportement.",
    "director.noTeachers": "Aucun enseignant encore — ajoutez-en un pour commencer.",
    "director.clearFilter": "Effacer le filtre",
    "director.teacherCount": "{count} enseignant(s)",
    "director.noTeachersWithStatus": "Aucun enseignant avec le statut \"{status}\"",
    "msg.title": "Messages",
    "msg.subtitle": "Communiquez avec votre équipe et vos élèves.",
    "msg.newMessage": "Nouveau message",
    "msg.sendTo": "Envoyer à",
    "msg.recipient": "Destinataire",
    "msg.message": "Message",
    "msg.placeholder": "Tapez votre message…",
    "msg.choose": "Choisir…",
    "msg.allTeachers": "Tous les enseignants",
    "msg.allStudents": "Tous les élèves",
    "msg.oneTeacher": "Un enseignant",
    "msg.oneStudent": "Un élève",
    "msg.inbox": "Boîte de réception",
    "msg.empty": "Aucun message pour l'instant",
    "msg.you": "Vous",
    "msg.to": "À",
    "chat.newChat": "Nouvelle conversation",
    "chat.contacts": "Contacts",
    "chat.selectChat": "Sélectionnez une conversation pour commencer à discuter",
    "chat.noConversations": "Aucune conversation pour l'instant",
    "chat.noContacts": "Aucun contact disponible",
    "chat.searchPlaceholder": "Rechercher…",
    "chat.typeMessage": "Tapez un message…",
    "chat.noResults": "Aucun résultat",
    "chat.online": "En ligne",
    "chat.yesterday": "Hier",
    "chat.sent": "Message envoyé",
    "chat.sendFailed": "Échec de l'envoi du message",
    "chat.loadFailed": "Échec du chargement des messages",
    "chat.you": "Vous",
    "chat.startConversation": "Dites bonjour pour lancer la conversation",
    "payment.currentPlan": "Plan actuel",
    "payment.manageSub": "Gérez votre abonnement et consultez l'historique des paiements.",
    "payment.chooseMethod": "Choisir le mode de paiement",
    "payment.selectMethod": "Sélectionnez comment vous souhaitez payer votre plan {plan}.",
    "payment.payInstantly": "Payez instantanément avec votre carte bancaire",
    "payment.secure": "Sécurisé et crypté",
    "payment.bankTransfer": "Virement bancaire",
    "payment.bankTransferDesc": "Transférez directement depuis votre compte bancaire",
    "payment.processingTime": "2-3 jours ouvrables",
    "payment.backToPlans": "Retour aux plans",
    "payment.backToMethods": "Retour aux modes",
    "payment.cardDetails": "Coordonnées bancaires",
    "payment.cardholderName": "Nom du titulaire",
    "payment.cardNumber": "Numéro de carte",
    "payment.expiry": "Expiration",
    "payment.cvv": "CVV",
    "payment.cardSecure": "Vos données bancaires sont cryptées et sécurisées",
    "payment.pay": "Payer {amount}",
    "payment.transferTo": "Virement vers",
    "payment.bank": "Banque",
    "payment.amount": "Montant",
    "payment.reference": "Référence",
    "payment.transferNote": "Veuillez inclure la référence dans votre virement pour que nous puissions identifier votre paiement. Votre abonnement sera activé dès réception du paiement (2-3 jours ouvrables).",
    "payment.confirmOrder": "Confirmer la commande",
    "payment.success": "Paiement réussi !",
    "payment.successTransfer": "Commande confirmée !",
    "payment.successMsg": "Votre plan {plan} est maintenant actif.",
    "payment.successTransferMsg": "Nous vous enverrons un email avec les détails du virement. Votre abonnement sera activé dès réception du paiement.",
    "payment.done": "Terminé",
    "payment.history": "Historique des paiements",
    "payment.noPayments": "Aucun paiement pour l'instant.",
    "payment.alreadyOnPlan": "Vous êtes déjà sur ce plan !",
    "analytics.title": "Analytiques",
    "analytics.subtitle": "Analyses et perspectives de performance scolaire.",
    "analytics.attendanceRate": "TAUX DE PRÉSENCE (30 JOURS)",
    "analytics.gradeDistribution": "Distribution des notes",
    "analytics.studentsPerSection": "Élèves par classe",
    "analytics.topStudents": "Top 5 des meilleurs élèves",
    "analytics.avgGrades": "Notes moyennes par matière",
    "analytics.noData": "Aucune donnée",
    "analytics.noGrades": "Aucune note",
    "analytics.noSections": "Aucune classe",
    "notifications.allCaughtUp": "Tout est à jour",
    "notifications.noNotifications": "Aucune notification",
    "notifications.markAllRead": "Tout marquer comme lu",
    "notifications.viewAll": "Voir tout",
    "parents.addParent": "Ajouter un parent",
    "parents.addParentDesc": "Créer un compte parent et lier aux élèves.",
    "parents.fullName": "Nom complet",
    "parents.emailOptional": "Email (optionnel)",
    "parents.phoneOptional": "Téléphone (optionnel)",
    "parents.role": "Parent",
    "parents.linkToStudents": "Lier aux élèves",
    "parents.noStudents": "Aucun élève",
    "parents.createAccount": "Créer le compte parent",
    "parents.manageDesc": "Gérer les comptes parents et les lier aux élèves.",
    "parents.noParents": "Aucun parent. Cliquez sur \"Ajouter un parent\" pour en créer un.",
    "parents.accountCreated": "Compte parent créé !",
    "parents.father": "Père",
    "parents.mother": "Mère",
    "parents.guardian": "Tuteur",
    "parents.noSection": "Aucune classe",
    "common.allSections": "Toutes les classes",
    "common.choose": "Choisir…",
    "common.student": "Élève",
    "common.section": "Classe",
    "common.name": "Nom",
    "common.date": "Date",
    "common.failed": "Échoué",
    "common.retry": "Réessayer",
    "common.home": "Aller à l'accueil",
    "error.title": "Une erreur s'est produite",
    "error.subtitle": "Une erreur inattendue s'est produite. Veuillez réessayer.",
    "common.title": "Titre",
    "common.content": "Contenu",
    "common.startTime": "Heure de début",
    "common.endTime": "Heure de fin",
    "teacher.overview.markedStatus": "Présence marquée {status} pour aujourd'hui",
    "teacher.overview.myAttendanceToday": "Ma présence — aujourd'hui",
    "teacher.overview.presentToday": "Présent aujourd'hui",
    "teacher.overview.markPresent": "Marquer présent",
    "teacher.overview.absentToday": "Absent aujourd'hui",
    "teacher.overview.markAbsent": "Marquer absent",
    "teacher.overview.notMarkedYet": "Vous n'avez pas encore marqué votre présence.",
    "teacher.overview.students": "Élèves",
    "teacher.overview.sections": "Classes",
    "teacher.overview.mySections": "Mes classes",
    "teacher.overview.studentsCount": "{count} élèves",
    "teacher.attendance.subtitle": "Marquez la présence quotidienne de vos élèves.",
    "teacher.attendance.total": "total",
    "teacher.attendance.noStudents": "Aucun élève dans votre classe pour le moment.",
    "teacher.grades.gradeAdded": "Note ajoutée",
    "teacher.grades.subtitle": "Ajoutez des notes et configurez les périodes d'examen.",
    "teacher.grades.periods": "Périodes",
    "teacher.grades.addGrade": "Ajouter une note",
    "teacher.grades.addGradeTitle": "Ajouter une note",
    "teacher.grades.examPeriods": "Périodes d'examen",
    "teacher.grades.noPeriods": "Aucune période. Cliquez sur \"Périodes\" pour en ajouter.",
    "teacher.grades.periodInfo": "×{coefficient} · {examCount} examens",
    "teacher.grades.allGrades": "Toutes les notes",
    "teacher.grades.noGrades": "Aucune note pour le moment.",
    "teacher.grades.noGradesSection": "Aucune note dans cette classe.",
    "teacher.grades.period": "Période",
    "teacher.grades.max": "Max",
    "teacher.grades.editPeriod": "Modifier la période",
    "teacher.grades.newExamPeriod": "Nouvelle période d'examen",
    "teacher.grades.start": "Début",
    "teacher.grades.end": "Fin",
    "teacher.grades.coefficient": "Coefficient",
    "teacher.grades.examCount": "Nombre d'examens",
    "teacher.grades.create": "Créer",
    "teacher.grades.periodUpdated": "Période mise à jour",
    "teacher.grades.periodCreated": "Période créée",
    "teacher.grades.deletePeriodConfirm": "Supprimer la période \"{name}\" ?",
    "teacher.grades.periodDeleted": "Période supprimée",
    "teacher.grades.subjectPlaceholder": "Mathématiques",
    "teacher.grades.namePlaceholder": "Semestre 1",
    "teacher.exams.examCreated": "Examen créé",
    "teacher.exams.deleteExamConfirm": "Supprimer cet examen ?",
    "teacher.exams.examDeleted": "Examen supprimé",
    "teacher.exams.failedLoadResults": "Échec du chargement des résultats",
    "teacher.exams.scoreSaved": "Note enregistrée",
    "teacher.exams.failedSaveScore": "Échec de l'enregistrement de la note",
    "teacher.exams.subtitle": "Créez et gérez les examens.",
    "teacher.exams.addExam": "Ajouter un examen",
    "teacher.exams.noExams": "Aucun examen. Cliquez sur \"Ajouter un examen\" pour en créer un.",
    "teacher.exams.noStudentsFound": "Aucun élève trouvé.",
    "teacher.exams.addExamTitle": "Ajouter un examen",
    "teacher.exams.namePlaceholder": "Examen du semestre",
    "teacher.exams.coefficient": "Coefficient",
    "teacher.exams.maxScore": "Note maximale",
    "teacher.homework.subtitle": "Créez et gérez les devoirs.",
    "teacher.homework.addHomework": "Ajouter un devoir",
    "teacher.homework.assignments": "Devoirs",
    "teacher.homework.noHomework": "Aucun devoir. Cliquez sur \"Ajouter un devoir\" pour en créer un.",
    "teacher.homework.noHomeworkSection": "Aucun devoir dans cette classe.",
    "teacher.homework.due": "Échéance",
    "teacher.homework.overdue": "En retard",
    "teacher.homework.submissionsCount": "{count} soumission(s)",
    "teacher.homework.attachedFile": "Fichier joint",
    "teacher.homework.noSubmissions": "Aucune soumission pour le moment.",
    "teacher.homework.submitted": "Soumis",
    "teacher.homework.attachment": "Pièce jointe",
    "teacher.homework.feedbackPlaceholder": "Commentaire...",
    "teacher.homework.update": "Mettre à jour",
    "teacher.homework.grade": "Noter",
    "teacher.homework.newHomework": "Nouveau devoir",
    "teacher.homework.titlePlaceholder": "Exercices du chapitre 5",
    "teacher.homework.descriptionPlaceholder": "Détails du devoir...",
    "teacher.homework.fileUrlOptional": "URL du fichier (optionnel)",
    "teacher.homework.create": "Créer",
    "teacher.homework.homeworkCreated": "Devoir créé",
    "teacher.homework.deleteConfirm": "Supprimer \"{title}\" ?",
    "teacher.homework.deleted": "Supprimé",
    "teacher.homework.graded": "Noté",
    "teacher.behavior.chooseStudent": "Choisissez un élève",
    "teacher.behavior.noteAdded": "Note de comportement ajoutée",
    "teacher.behavior.subtitle": "Suivez les notes de comportement de vos élèves.",
    "teacher.behavior.note": "note",
    "teacher.behavior.noNotes": "Aucune note de comportement pour le moment.",
    "teacher.behavior.addNoteTitle": "Ajouter une note de comportement",
    "teacher.behavior.type": "Type",
    "teacher.behavior.positive": "Positif",
    "teacher.behavior.neutral": "Neutre",
    "teacher.behavior.negative": "Négatif",
    "teacher.behavior.noteLabel": "Note",
    "teacher.behavior.notePlaceholder": "Décrivez le comportement…",
    "messages.chooseStudent": "Choisissez un élève",
    "teacher.messages.sent": "Message envoyé",
    "teacher.messages.sendFailed": "Échec de l'envoi",
    "teacher.messages.subtitle": "Communiquez avec votre directeur et vos élèves.",
    "teacher.messages.newMessage": "Nouveau message",
    "teacher.messages.sendTo": "Envoyer à",
    "teacher.messages.director": "Directeur",
    "teacher.messages.allStudents": "Tous les élèves",
    "teacher.messages.oneStudent": "Un élève",
    "teacher.messages.messageLabel": "Message",
    "teacher.messages.placeholder": "Tapez votre message…",
    "teacher.messages.inbox": "Boîte de réception",
    "teacher.lessons.lessonCreated": "Leçon créée",
    "teacher.lessons.deleteConfirm": "Supprimer cette leçon ?",
    "teacher.lessons.lessonDeleted": "Leçon supprimée",
    "teacher.lessons.subtitle": "Créez et gérez les leçons pour vos classes.",
    "teacher.lessons.addLesson": "Ajouter une leçon",
    "teacher.lessons.noLessonsSection": "Aucune leçon dans cette classe.",
    "teacher.lessons.noLessons": "Aucune leçon. Cliquez sur \"Ajouter une leçon\" pour en créer une.",
    "teacher.lessons.noContent": "Aucun contenu.",
    "teacher.lessons.file": "Fichier",
    "teacher.lessons.video": "Vidéo",
    "teacher.lessons.addLessonTitle": "Ajouter une leçon",
    "teacher.lessons.titlePlaceholder": "Titre de la leçon",
    "teacher.lessons.contentPlaceholder": "Contenu de la leçon…",
    "teacher.lessons.fileUrlOptional": "URL du fichier (optionnel)",
    "teacher.lessons.videoUrlOptional": "URL de la vidéo (optionnel)",
    "teacher.sections.sectionAdded": "Classe ajoutée",
    "teacher.sections.deleteConfirm": "Supprimer la classe {name} ?",
    "teacher.sections.sectionDeleted": "Classe supprimée",
    "teacher.sections.deleteFailed": "Échec de la suppression",
    "teacher.sections.subtitle": "Gérez vos classes.",
    "teacher.sections.section": "classe",
    "teacher.sections.noSections": "Aucune classe pour le moment.",
    "teacher.sections.studentsCount": "{count} élèves",
    "teacher.sections.addSectionTitle": "Ajouter une classe",
    "teacher.sections.sectionName": "Nom de la classe",
    "teacher.students.studentAdded": "Élève ajouté !",
    "teacher.students.deleteConfirm": "Supprimer {name} ?",
    "teacher.students.studentDeleted": "Élève supprimé",
    "teacher.students.deleteFailed": "Échec de la suppression",
    "teacher.students.passwordReset": "Mot de passe réinitialisé",
    "teacher.students.subtitle": "Gérez vos élèves.",
    "teacher.students.importPdf": "Importer PDF",
    "teacher.students.noStudents": "Aucun élève pour le moment.",
    "teacher.students.addStudentTitle": "Ajouter un élève",
    "teacher.students.firstName": "Prénom",
    "teacher.students.lastName": "Nom",
    "teacher.students.serialNumber": "N° matricule",
    "teacher.students.noSection": "Aucune classe",
    "teacher.students.emailPasswordInfo": "Un email et un mot de passe seront générés. Partagez-les avec l'élève pour se connecter.",
    "teacher.students.credentialsTitle": "Identifiants de l'élève",
    "director.exams.overview": "Aperçu de tous les examens par classe.",
    "director.exams.allSections": "Toutes les classes",
    "director.exams.total": "Total",
    "director.exams.graded": "Corrigés",
    "director.exams.pending": "En attente",
    "director.exams.noExamsInSection": "Aucun examen dans cette classe.",
    "director.exams.noExams": "Aucun examen pour le moment.",
    "director.exams.deleteConfirm": "Supprimer l'examen « {name} » ? Cette action est irréversible.",
    "director.exams.deleteSuccess": "Examen supprimé",
    "director.exams.deleteFailed": "Échec de la suppression",
    "director.exams.editTitle": "Modifier l'examen",
    "director.exams.updateSuccess": "Examen mis à jour",
    "director.exams.updateFailed": "Échec de la mise à jour",
    "director.payment.fillAllFields": "Veuillez remplir tous les champs de la carte",
    "director.payment.failed": "Échec du paiement",
    "director.payment.freeTrial": "Essai gratuit",
    "director.payment.active": "ACTIF",
    "director.payment.card": "carte",
    "director.analytics.loadFailed": "Échec du chargement des analytiques",
    "director.analytics.noDataAvailable": "Aucune donnée disponible",
    "director.analytics.retry": "Réessayer",
    "director.teachers.couldNotCopy": "Impossible de copier",
    "director.teachers.addSuccess": "Enseignant ajouté. Partagez les identifiants ci-dessous.",
    "director.teachers.addFailed": "Échec",
    "director.teachers.deleteConfirm": "Supprimer l'enseignant {name} ? Cette action est irréversible.",
    "director.teachers.deleteSuccess": "Enseignant supprimé",
    "director.teachers.deleteFailed": "Échec de la suppression",
    "director.teachers.subtitle": "Ajoutez des enseignants et partagez les identifiants générés automatiquement.",
    "director.teachers.addTeacherBtn": "Ajouter un enseignant",
    "director.teachers.noTeachers": "Aucun enseignant. Cliquez sur « Ajouter un enseignant » pour commencer.",
    "director.teachers.name": "Nom",
    "director.teachers.subject": "Matière",
    "director.teachers.email": "Email",
    "director.teachers.password": "Mot de passe",
    "director.teachers.students": "Élèves",
    "director.teachers.actions": "Actions",
    "director.teachers.modalTitleAdd": "Ajouter un enseignant",
    "director.teachers.modalTitleAdded": "Enseignant ajouté",
    "director.teachers.credentialsNote": "a été ajouté. Partagez ces identifiants avec lui — ils ne seront plus affichés.",
    "director.teachers.done": "Terminé",
    "director.teachers.firstName": "Prénom",
    "director.teachers.lastName": "Nom",
    "director.teachers.subjectLabel": "Matière",
    "director.teachers.autoGenerate": "Un email unique et un mot de passe de 10 caractères seront générés automatiquement pour cet enseignant.",
    "director.students.subtitle": "Tous les élèves de tous les enseignants.",
    "director.students.noStudents": "Aucun élève pour le moment.",
    "director.students.unassigned": "Non assigné",
    "director.students.grades": "notes",
    "director.students.present": "présent",
    "director.students.absent": "absent",
    "director.students.notes": "notes",
    "director.students.password": "Mot de passe :",
    "director.students.viewDetails": "Voir les détails",
    "director.students.student": "Élève",
    "director.students.avg": "Moy.",
    "director.students.presentLabel": "Présent",
    "director.students.absentLabel": "Absent",
    "director.students.notesLabel": "Notes",
    "director.students.gradesTitle": "Notes",
    "director.students.behaviorTitle": "Notes de comportement",
    "director.students.nothingHere": "Rien ici pour le moment.",
    "director.messages.chooseRecipient": "Veuillez choisir un destinataire",
    "director.messages.sent": "Message envoyé",
    "director.messages.sendFailed": "Échec de l'envoi",
    "director.notifications.loadFailed": "Échec du chargement des notifications",
    "director.notifications.unreadCount": "{count} non lue(s)",
    "director.notifications.retry": "Réessayer",
    "student.overview.welcome": "Bienvenue, {name} 👋",
    "student.overview.dashboardSubtitle": "Votre tableau de bord élève",
    "student.overview.overallAvg": "Moy. générale",
    "student.overview.present": "Présent",
    "student.overview.grades": "Notes",
    "student.overview.notes": "Notes",
    "student.overview.recentGrades": "Notes récentes",
    "student.overview.noGrades": "Aucune note pour le moment.",
    "student.overview.behaviorNotes": "Notes de comportement",
    "student.overview.noBehaviorNotes": "Aucune note de comportement.",
    "student.overview.recentMessages": "Messages récents",
    "student.overview.from": "De",
    "student.overview.retry": "Réessayer",
    "student.reportCard.retry": "Réessayer",
    "student.reportCard.title": "Bulletin",
    "student.reportCard.subtitle": "Résumé de performance académique",
    "student.reportCard.downloadPdf": "Télécharger PDF",
    "student.reportCard.emptyState": "Aucune note enregistrée. Le bulletin sera disponible une fois les notes saisies.",
    "student.reportCard.student": "Élève",
    "student.reportCard.teacher": "Enseignant :",
    "student.reportCard.overallAverage": "Moyenne générale",
    "student.reportCard.periodAverage": "Moyenne de la période",
    "student.reportCard.subject": "Matière",
    "student.reportCard.score": "Note",
    "student.reportCard.grade": "Mention",
    "student.reportCard.excellent": "Excellent",
    "student.reportCard.passing": "Passable",
    "student.reportCard.needsImprovement": "À améliorer",
    "student.reportCard.weightedAverage": "Moyenne pondérée :",
    "student.reportCard.examCount": "examen(s)",
    "student.homework.submitted": "Soumis",
    "student.homework.failed": "Échoué",
    "student.homework.subtitle": "Consultez et soumettez vos devoirs.",
    "student.homework.noHomework": "Aucun devoir assigné pour le moment.",
    "student.homework.teacher": "Enseignant :",
    "student.homework.due": "Échéance :",
    "student.homework.section": "Classe :",
    "student.homework.attachment": "Pièce jointe",
    "student.homework.submit": "Soumettre",
    "student.homework.feedback": "Commentaire",
    "student.homework.graded": "Noté",
    "student.homework.submittedWaiting": "Soumis — en attente de correction.",
    "student.homework.submitHomework": "Soumettre le devoir",
    "student.homework.yourAnswer": "Votre réponse",
    "student.homework.answerPlaceholder": "Écrivez votre réponse ici...",
    "student.homework.fileUrlOptional": "URL du fichier (optionnel)",
    "student.homework.cancel": "Annuler",
    "student.homework.overdue": "En retard",
    "student.homework.pending": "En attente",
    "student.exams.retry": "Réessayer",
    "student.exams.title": "Examens",
    "student.exams.subtitle": "Vos résultats et notes d'examen.",
    "student.exams.noExams": "Aucun examen pour le moment.",
    "student.exams.pending": "En attente",
    "student.exams.graded": "Corrigé",
    "student.grades.retry": "Réessayer",
    "student.grades.title": "Mes notes",
    "student.grades.subtitle": "Toutes vos notes et moyennes.",
    "student.grades.overallAverage": "Moyenne générale",
    "student.grades.noGrades": "Aucune note pour le moment.",
    "student.grades.average": "Moyenne",
    "student.grades.noGradesPeriod": "Aucune note dans cette période.",
    "student.attendance.retry": "Réessayer",
    "student.attendance.title": "Ma présence",
    "student.attendance.subtitle": "Votre historique de présence.",
    "student.attendance.present": "Présent",
    "student.attendance.absent": "Absent",
    "student.attendance.noRecords": "Aucun enregistrement de présence.",
    "student.behavior.retry": "Réessayer",
    "student.behavior.title": "Notes de comportement",
    "student.behavior.subtitle": "Notes de vos enseignants.",
    "student.behavior.noNotes": "Aucune note de comportement. Continuez vos efforts !",
    "student.messages.sent": "Message envoyé à vos enseignants",
    "student.messages.sendFailed": "Échec de l'envoi",
    "student.messages.title": "Messages",
    "student.messages.subtitle": "Communiquez avec vos enseignants et directeur.",
    "student.messages.newMessage": "Nouveau message",
    "student.messages.to": "À",
    "student.messages.allTeachers": "Tous vos enseignants",
    "student.messages.message": "Message",
    "student.messages.placeholder": "Tapez votre message…",
    "student.messages.send": "Envoyer",
    "student.messages.conversation": "Conversation",
    "student.messages.retry": "Réessayer",
    "student.messages.noMessages": "Aucun message pour l'instant",
    "student.messages.you": "Vous",
    "student.lessons.retry": "Réessayer",
    "student.lessons.title": "Leçons",
    "student.lessons.subtitle": "Parcourez les leçons de votre classe.",
    "student.lessons.noLessons": "Aucune leçon disponible pour le moment.",
    "student.lessons.noContent": "Aucun contenu.",
    "student.lessons.file": "Fichier",
    "student.lessons.video": "Vidéo",
  },
  ar: {
    "nav.features": "الميزات",
    "nav.pricing": "الأسعار",
    "nav.about": "حول",
    "nav.signin": "تسجيل الدخول",
    "nav.start": "ابدأ مجاناً",
    "hero.badge": "مصمم للمدارس المغربية",
    "hero.title": "استبدل الورق — نمّ مدرستك",
    "hero.subtitle":
      "إدوويف هي المنصة الشاملة لمديري المدارس الخاصة والمعلمين في المغرب: الحضور والدرجات والسلوك — من أي جهاز.",
    "hero.cta": "ابدأ تجربتك المجانية لمدة 15 يوماً",
    "hero.secondary": "شاهد كيف يعمل",
    "hero.note": "بدون بطاقة ائتمان • إلغاء في أي وقت",
    "features.title": "مصمم للطريقة التي تعمل بها المدارس المغربية",
    "features.subtitle": "كل ما تحتاجه لإدارة مدرسة حديثة، مصمم للهاتف أولاً.",
    "feat.attendance.title": "حضور في الوقت الفعلي",
    "feat.attendance.desc": "سجّل الحضور في ثوانٍ من أي جهاز. المدير يرى المدرسة كاملة بنظرة واحدة.",
    "feat.grades.title": "دفتر نقاط ذكي",
    "feat.grades.desc": "فترات قابلة للتكوين، معاملات، وحساب تلقائي للمعدلات.",
    "feat.behavior.title": "تتبع السلوك",
    "feat.behavior.desc": "ملاحظات سلوك يومية ترافق الطالب طوال السنة.",
    "feat.messaging.title": "رسائل مباشرة",
    "feat.messaging.desc": "تواصل بين المدير والمعلم والطالب في مكان واحد.",
    "feat.import.title": "استيراد جماعي من PDF",
    "feat.import.desc": "ارفع قائمة الفصل وسنستخرج كل طالب تلقائياً.",
    "feat.multilang.title": "عربية، فرنسية، إنجليزية",
    "feat.multilang.desc": "د كامل للـ RTL وتفضيلات لغة مستمرة لكل مستخدم.",
    "pricing.title": "أسعار بسيطة وعادلة",
    "pricing.subtitle": "15 يوماً تجربة مجانية. بدون بطاقة ائتمان.",
    "pricing.monthly": "شهري",
    "pricing.annual": "سنوي",
    "pricing.save": "وفّر 50%",
    "pricing.cta": "ابدأ تجربتك المجانية لمدة 15 يوماً",
    "pricing.choose": "اختر",
    "pricing.perMonth": "/شهر",
    "pricing.perYear": "/سنة",
    "pricing.mostPopular": "الأكثر شيوعاً",
    "feat.list.1": "معلمون وطلاب غير محدودين",
    "feat.list.2": "استيراد PDF جماعي",
    "feat.list.3": "رسائل مباشرة",
    "feat.list.4": "وصول من الجوال والحاسوب",
    "feat.list.5": "دعم ذو أولوية",
    "footer.tagline": "مصمم بعناية للمدارس الخاصة المغربية.",
    "footer.contact": "اتصل بنا",
    "footer.legal": "قانوني",
    "footer.privacy": "الخصوصية",
    "footer.terms": "الشروط",
    "footer.copyright": "© 2026 إدوويف. جميع الحقوق محفوظة.",
    "common.signin": "تسجيل الدخول",
    "common.signup": "إنشاء حساب",
    "common.email": "البريد الإلكتروني",
    "common.phone": "الهاتف",
    "common.password": "كلمة المرور",
    "common.fullName": "الاسم الكامل",
    "common.schoolName": "اسم المدرسة",
    "common.description": "الوصف",
    "common.uploadLogo": "تحميل شعار المدرسة",
    "common.continue": "متابعة",
    "common.back": "رجوع",
    "common.signinGoogle": "تسجيل الدخول بـ Google",
    "common.signupGoogle": "إنشاء حساب بـ Google",
    "common.or": "أو",
    "common.newHere": "جديد هنا؟",
    "common.alreadyAccount": "لديك حساب بالفعل؟",
    "auth.welcomeBack": "مرحباً بعودتك",
    "auth.welcomeBackSub": "سجّل الدخول إلى حسابك في إدوويف",
    "auth.createAccount": "أنشئ حساب مدرستك",
    "auth.createAccountSub": "أنشئ مدرستك في أقل من دقيقتين",
    "auth.welcomeDirector": "مدير",
    "auth.welcomeTeacher": "معلم",
    "auth.welcomeAdmin": "المسؤول",
    "auth.welcomeStudent": "طالب",
    "auth.welcomeParent": "ولي الأمر",
    "auth.verifyEmail": "تحقق من بريدك الإلكتروني",
    "auth.verifyEmailSub": "أرسلنا رابط التحقق إلى {email}. اضغط على الرابط لتفعيل حسابك في إدوويف.",
    "auth.resendEmail": "إعادة إرسال البريد",
    "auth.resendSent": "تم إرسال بريد التحقق. تحقق من صندوق الوارد.",
    "auth.resendFailed": "فشل الإرسال. حاول مرة أخرى.",
    "auth.needVerify": "يرجى التحقق من بريدك الإلكتروني قبل تسجيل الدخول.",
    "auth.verifying": "جارٍ التحقق من بريدك الإلكتروني...",
    "auth.verifySuccess": "تم التحقق من البريد! يتم تحويلك إلى لوحة التحكم...",
    "auth.verifyInvalid": "رابط التحقق هذا غير صالح.",
    "auth.verifyExpired": "انتهت صلاحية رابط التحقق. اطلب رابطًا جديدًا أدناه.",
    "auth.verifyGoToDashboard": "الانتقال إلى لوحة التحكم",
    "auth.verifyHint": "تم إرسال رابط التحقق إلى بريدك الإلكتروني. تحقق من صندوق الوارد (والبريد غير المرغوب فيه).",
    "dashboard.overview": "نظرة عامة",
    "dashboard.teachers": "المعلمون",
    "dashboard.students": "الطلاب",
    "dashboard.messages": "الرسائل",
    "dashboard.payment": "الدفع",
    "dashboard.sections": "الأقسام",
    "dashboard.grades": "الدرجات",
    "dashboard.attendance": "الحضور",
    "dashboard.behavior": "السلوك",
    "dashboard.homework": "الواجبات",
    "dashboard.notifications": "الإشعارات",
    "dashboard.lessons": "الدروس",
    "dashboard.exams": "الامتحانات",
    "dashboard.reportCard": "كشف النقط",
    "dashboard.analytics": "التحليلات",
    "dashboard.parents": "أولياء الأمور",
    "common.relation": "العلاقة",
    "common.dueDate": "تاريخ التسليم",
    "common.subject": "المادة",
    "common.room": "القاعة",
    "common.day": "اليوم",
    "common.time": "الوقت",
    "common.feedback": "التعليق",
    "common.submit": "تسليم",
    "common.score": "النقطة",
    "common.maxScore": "النقطة القصوى",
    "common.remarks": "ملاحظات",
    "common.download": "تحميل",
    "common.upload": "رفع",
    "common.gradedAt": "تاريخ التصحيح",
    "dashboard.admin": "المسؤول",
    "common.search": "بحث",
    "common.add": "إضافة",
    "common.delete": "حذف",
    "common.edit": "تعديل",
    "common.save": "حفظ",
    "common.cancel": "إلغاء",
    "common.send": "إرسال",
    "common.loading": "جاري التحميل...",
    "common.empty": "لا يوجد شيء هنا بعد",
    "common.theme.light": "فاتح",
    "common.theme.dark": "داكن",
    "common.language": "اللغة",
    "common.signout": "تسجيل الخروج",
    "common.profile": "الملف الشخصي",
    "trial.daysLeft": "تجربة مجانية • {count} يوم متبقي",
    "trial.upgrade": "ترقية الآن",
    "trial.upgradeCta": "ترقية للاستمرار في استخدام إدوويف →",
    "stat.teachers": "المعلمون",
    "stat.students": "الطلاب",
    "stat.sections": "الأقسام",
    "stat.todayPresent": "الحاضرون اليوم",
    "attendance.title": "حضور المعلمين — اليوم",
    "attendance.manageTeachers": "إدارة المعلمين →",
    "attendance.present": "حاضر",
    "attendance.absent": "غائب",
    "attendance.notMarked": "غير مسجل",
    "status.PRESENT": "حاضر",
    "status.ABSENT": "غائب",
    "status.UNKNOWN": "غير مسجل",
    "director.welcomeBack": "مرحباً بعودتك، {name}. إليك ما يحدث اليوم.",
    "director.quickAction": "إجراء سريع",
    "director.addTeacher": "إضافة معلم",
    "director.addTeacherDesc": "إنشاء تلقائي للبريد الإلكتروني وكلمة المرور للمشاركة.",
    "director.browseStudents": "تصفح الطلاب",
    "director.browseStudentsDesc": "عرض الدرجات والحضور والسلوك.",
    "director.noTeachers": "لا يوجد معلمون بعد — أضف واحداً للبدء.",
    "director.clearFilter": "مسح الفلتر",
    "director.teacherCount": "{count} معلم(ين)",
    "director.noTeachersWithStatus": "لا يوجد معلمون بالحالة \"{status}\"",
    "msg.title": "الرسائل",
    "msg.subtitle": "تواصل مع فريقك وطلابك.",
    "msg.newMessage": "رسالة جديدة",
    "msg.sendTo": "إرسال إلى",
    "msg.recipient": "المستلم",
    "msg.message": "الرسالة",
    "msg.placeholder": "اكتب رسالتك…",
    "msg.choose": "اختر…",
    "msg.allTeachers": "كل المعلمين",
    "msg.allStudents": "كل الطلاب",
    "msg.oneTeacher": "معلم واحد",
    "msg.oneStudent": "طالب واحد",
    "msg.inbox": "الوارد",
    "msg.empty": "لا توجد رسائل بعد",
    "msg.you": "أنت",
    "msg.to": "إلى",
    "chat.newChat": "محادثة جديدة",
    "chat.contacts": "جهات الاتصال",
    "chat.selectChat": "اختر محادثة لبدء المراسلة",
    "chat.noConversations": "لا توجد محادثات بعد",
    "chat.noContacts": "لا توجد جهات اتصال متاحة",
    "chat.searchPlaceholder": "ابحث…",
    "chat.typeMessage": "اكتب رسالتك…",
    "chat.noResults": "لا توجد نتائج",
    "chat.online": "متصل الآن",
    "chat.yesterday": "أمس",
    "chat.sent": "تم إرسال الرسالة",
    "chat.sendFailed": "فشل إرسال الرسالة",
    "chat.loadFailed": "فشل تحميل الرسائل",
    "chat.you": "أنت",
    "chat.startConversation": "ابدأ بتحية لبدء المحادثة",
    "payment.currentPlan": "الاشتراك الحالي",
    "payment.manageSub": "أدر اشتراكك وعرض سجل المدفوعات.",
    "payment.chooseMethod": "اختر طريقة الدفع",
    "payment.selectMethod": "اختر كيف تريد الدفع مقابل اشتراك {plan}.",
    "payment.payInstantly": "ادفع فوراً ببطاقتك الائتمانية",
    "payment.secure": "آمن ومشفر",
    "payment.bankTransfer": "تحويل بنكي",
    "payment.bankTransferDesc": "تحويل مباشرة من حسابك البنكي",
    "payment.processingTime": "2-3 أيام عمل",
    "payment.backToPlans": "العودة للباقات",
    "payment.backToMethods": "العودة للطرق",
    "payment.cardDetails": "بيانات البطاقة",
    "payment.cardholderName": "اسم حامل البطاقة",
    "payment.cardNumber": "رقم البطاقة",
    "payment.expiry": "تاريخ الانتهاء",
    "payment.cvv": "CVV",
    "payment.cardSecure": "بيانات بطاقتك مشفرة وآمنة",
    "payment.pay": "ادفع {amount}",
    "payment.transferTo": "تحويل إلى",
    "payment.bank": "البنك",
    "payment.amount": "المبلغ",
    "payment.reference": "المرجع",
    "payment.transferNote": "يرجى إدراج المرجع في التحويل حتى نتمكن من مطابقة الدفع. سيتم تفعيل اشتراكك عند استلام الدفع (2-3 أيام عمل).",
    "payment.confirmOrder": "تأكيد الطلب",
    "payment.success": "تم الدفع بنجاح!",
    "payment.successTransfer": "تم تأكيد الطلب!",
    "payment.successMsg": "اشتراك {plan} الآن نشط.",
    "payment.successTransferMsg": "سنرسل لك بريداً إلكترونياً بتفاصيل التحويل البنكي. سيتم تفعيل اشتراكك عند استلام الدفع.",
    "payment.done": "تم",
    "payment.history": "سجل المدفوعات",
    "payment.noPayments": "لا توجد مدفوعات بعد.",
    "payment.alreadyOnPlan": "أنت بالفعل على هذا الاشتراك!",
    "analytics.title": "التحليلات",
    "analytics.subtitle": "تحليلات وأفكار أداء المدرسة.",
    "analytics.attendanceRate": "معدل الحضور (30 يوم)",
    "analytics.gradeDistribution": "توزيع الدرجات",
    "analytics.studentsPerSection": "الطلاب حسب القسم",
    "analytics.topStudents": "أفضل 5 طلاب أداء",
    "analytics.avgGrades": "متوسط الدرجات حسب المادة",
    "analytics.noData": "لا توجد بيانات بعد",
    "analytics.noGrades": "لا توجد درجات بعد",
    "analytics.noSections": "لا توجد أقسام",
    "notifications.allCaughtUp": "كل شيء محدّث",
    "notifications.noNotifications": "لا توجد إشعارات بعد",
    "notifications.markAllRead": "تعليم الكل كمقروء",
    "notifications.viewAll": "عرض الكل",
    "parents.addParent": "إضافة ولي أمر",
    "parents.addParentDesc": "إنشاء حساب ولي أمر وربطه بالطلاب.",
    "parents.fullName": "الاسم الكامل",
    "parents.emailOptional": "البريد الإلكتروني (اختياري)",
    "parents.phoneOptional": "الهاتف (اختياري)",
    "parents.role": "ولي أمر",
    "parents.linkToStudents": "ربط بالطلاب",
    "parents.noStudents": "لا يوجد طلاب",
    "parents.createAccount": "إنشاء حساب ولي الأمر",
    "parents.manageDesc": "إدارة حسابات أولياء الأمور وربطها بالطلاب.",
    "parents.noParents": "لا يوجد أولياء أمر بعد. اضغط \"إضافة ولي أمر\" لإنشاء واحد.",
    "parents.accountCreated": "تم إنشاء حساب ولي الأمر!",
    "parents.father": "الأب",
    "parents.mother": "الأم",
    "parents.guardian": "الوصي",
    "parents.noSection": "لا يوجد قسم",
    "common.allSections": "كل الأقسام",
    "common.choose": "اختر…",
    "common.student": "طالب",
    "common.section": "القسم",
    "common.name": "الاسم",
    "common.date": "التاريخ",
    "common.failed": "فشل",
    "common.retry": "إعادة المحاولة",
    "common.home": "العودة إلى الصفحة الرئيسية",
    "error.title": "حدث خطأ ما",
    "error.subtitle": "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
    "common.title": "العنوان",
    "common.content": "المحتوى",
    "common.startTime": "وقت البداية",
    "common.endTime": "وقت النهاية",
    "teacher.overview.markedStatus": "تم تسجيل {status} لليوم",
    "teacher.overview.myAttendanceToday": "حضوري — اليوم",
    "teacher.overview.presentToday": "حاضر اليوم",
    "teacher.overview.markPresent": "تسجيل حضور",
    "teacher.overview.absentToday": "غائب اليوم",
    "teacher.overview.markAbsent": "تسجيل غياب",
    "teacher.overview.notMarkedYet": "لم تسجل حضورك بعد.",
    "teacher.overview.students": "الطلاب",
    "teacher.overview.sections": "الأقسام",
    "teacher.overview.mySections": "أقسامي",
    "teacher.overview.studentsCount": "{count} طالب(ين)",
    "teacher.attendance.subtitle": "سجّل الحضور اليومي لطلابك.",
    "teacher.attendance.total": "المجموع",
    "teacher.attendance.noStudents": "لا يوجد طلاب في فصلك بعد.",
    "teacher.grades.gradeAdded": "تمت إضافة النقطة",
    "teacher.grades.subtitle": "أضف الدرجات وقم بتكوين فترات الامتحان.",
    "teacher.grades.periods": "الفترات",
    "teacher.grades.addGrade": "إضافة نقطة",
    "teacher.grades.addGradeTitle": "إضافة نقطة",
    "teacher.grades.examPeriods": "فترات الامتحان",
    "teacher.grades.noPeriods": "لا توجد فترات. اضغط \"الفترات\" لإضافة واحدة.",
    "teacher.grades.periodInfo": "×{coefficient} · {examCount} امتحانات",
    "teacher.grades.allGrades": "كل الدرجات",
    "teacher.grades.noGrades": "لا توجد درجات بعد.",
    "teacher.grades.noGradesSection": "لا توجد درجات في هذا القسم.",
    "teacher.grades.period": "الفترة",
    "teacher.grades.max": "القصوى",
    "teacher.grades.editPeriod": "تعديل الفترة",
    "teacher.grades.newExamPeriod": "فترة امتحان جديدة",
    "teacher.grades.start": "البداية",
    "teacher.grades.end": "النهاية",
    "teacher.grades.coefficient": "المعامل",
    "teacher.grades.examCount": "عدد الامتحانات",
    "teacher.grades.create": "إنشاء",
    "teacher.grades.periodUpdated": "تم تحديث الفترة",
    "teacher.grades.periodCreated": "تم إنشاء الفترة",
    "teacher.grades.deletePeriodConfirm": "حذف الفترة \"{name}\"؟",
    "teacher.grades.periodDeleted": "تم حذف الفترة",
    "teacher.grades.subjectPlaceholder": "رياضيات",
    "teacher.grades.namePlaceholder": "الفصل الأول",
    "teacher.exams.examCreated": "تم إنشاء الامتحان",
    "teacher.exams.deleteExamConfirm": "حذف هذا الامتحان؟",
    "teacher.exams.examDeleted": "تم حذف الامتحان",
    "teacher.exams.failedLoadResults": "فشل تحميل النتائج",
    "teacher.exams.scoreSaved": "تم حفظ النقطة",
    "teacher.exams.failedSaveScore": "فشل حفظ النقطة",
    "teacher.exams.subtitle": "أنشئ وأدر الامتحانات.",
    "teacher.exams.addExam": "إضافة امتحان",
    "teacher.exams.noExams": "لا توجد امتحانات. اضغط \"إضافة امتحان\" لإنشاء واحد.",
    "teacher.exams.noStudentsFound": "لم يتم العثور على طلاب.",
    "teacher.exams.addExamTitle": "إضافة امتحان",
    "teacher.exams.namePlaceholder": "امتحان منتصف الفصل",
    "teacher.exams.coefficient": "المعامل",
    "teacher.exams.maxScore": "النقطة القصوى",
    "teacher.homework.subtitle": "أنشئ وأدر الواجبات.",
    "teacher.homework.addHomework": "إضافة واجب",
    "teacher.homework.assignments": "الواجبات",
    "teacher.homework.noHomework": "لا توجد واجبات. اضغط \"إضافة واجب\" لإنشاء واحد.",
    "teacher.homework.noHomeworkSection": "لا توجد واجبات في هذا القسم.",
    "teacher.homework.due": "التسليم",
    "teacher.homework.overdue": "متأخر",
    "teacher.homework.submissionsCount": "{count} تسليم(ات)",
    "teacher.homework.attachedFile": "ملف مرفق",
    "teacher.homework.noSubmissions": "لا توجد تسليمات بعد.",
    "teacher.homework.submitted": "تم التسليم",
    "teacher.homework.attachment": "مرفق",
    "teacher.homework.feedbackPlaceholder": "تعليق...",
    "teacher.homework.update": "تحديث",
    "teacher.homework.grade": "تصحيح",
    "teacher.homework.newHomework": "واجب جديد",
    "teacher.homework.titlePlaceholder": "تمارين الفصل 5",
    "teacher.homework.descriptionPlaceholder": "تفاصيل الواجب...",
    "teacher.homework.fileUrlOptional": "رابط الملف (اختياري)",
    "teacher.homework.create": "إنشاء",
    "teacher.homework.homeworkCreated": "تم إنشاء الواجب",
    "teacher.homework.deleteConfirm": "حذف \"{title}\"؟",
    "teacher.homework.deleted": "تم الحذف",
    "teacher.homework.graded": "تم التصحيح",
    "teacher.behavior.chooseStudent": "اختر طالباً",
    "teacher.behavior.noteAdded": "تمت إضافة ملاحظة السلوك",
    "teacher.behavior.subtitle": "تتبع ملاحظات السلوك لطلابك.",
    "teacher.behavior.note": "ملاحظة",
    "teacher.behavior.noNotes": "لا توجد ملاحظات سلوك بعد.",
    "teacher.behavior.addNoteTitle": "إضافة ملاحظة سلوك",
    "teacher.behavior.type": "النوع",
    "teacher.behavior.positive": "إيجابي",
    "teacher.behavior.neutral": "محايد",
    "teacher.behavior.negative": "سلبي",
    "teacher.behavior.noteLabel": "الملاحظة",
    "teacher.behavior.notePlaceholder": "صف السلوك…",
    "messages.chooseStudent": "اختر طالباً",
    "teacher.messages.sent": "تم إرسال الرسالة",
    "teacher.messages.sendFailed": "فشل الإرسال",
    "teacher.messages.subtitle": "تواصل مع مديرك وطلابك.",
    "teacher.messages.newMessage": "رسالة جديدة",
    "teacher.messages.sendTo": "إرسال إلى",
    "teacher.messages.director": "المدير",
    "teacher.messages.allStudents": "كل الطلاب",
    "teacher.messages.oneStudent": "طالب واحد",
    "teacher.messages.messageLabel": "الرسالة",
    "teacher.messages.placeholder": "اكتب رسالتك…",
    "teacher.messages.inbox": "الوارد",
    "teacher.lessons.lessonCreated": "تم إنشاء الدرس",
    "teacher.lessons.deleteConfirm": "حذف هذا الدرس؟",
    "teacher.lessons.lessonDeleted": "تم حذف الدرس",
    "teacher.lessons.subtitle": "أنشئ وأدر الدروس لأقسامك.",
    "teacher.lessons.addLesson": "إضافة درس",
    "teacher.lessons.noLessonsSection": "لا توجد دروس في هذا القسم.",
    "teacher.lessons.noLessons": "لا توجد دروس. اضغط \"إضافة درس\" لإنشاء واحد.",
    "teacher.lessons.noContent": "لا يوجد محتوى.",
    "teacher.lessons.file": "ملف",
    "teacher.lessons.video": "فيديو",
    "teacher.lessons.addLessonTitle": "إضافة درس",
    "teacher.lessons.titlePlaceholder": "عنوان الدرس",
    "teacher.lessons.contentPlaceholder": "محتوى الدرس…",
    "teacher.lessons.fileUrlOptional": "رابط الملف (اختياري)",
    "teacher.lessons.videoUrlOptional": "رابط الفيديو (اختياري)",
    "teacher.sections.sectionAdded": "تمت إضافة القسم",
    "teacher.sections.deleteConfirm": "حذف القسم {name}؟",
    "teacher.sections.sectionDeleted": "تم حذف القسم",
    "teacher.sections.deleteFailed": "فشل الحذف",
    "teacher.sections.subtitle": "أدر أقسامك.",
    "teacher.sections.section": "قسم",
    "teacher.sections.noSections": "لا توجد أقسام بعد.",
    "teacher.sections.studentsCount": "{count} طالب(ين)",
    "teacher.sections.addSectionTitle": "إضافة قسم",
    "teacher.sections.sectionName": "اسم القسم",
    "teacher.students.studentAdded": "تمت إضافة الطالب!",
    "teacher.students.deleteConfirm": "حذف {name}؟",
    "teacher.students.studentDeleted": "تم حذف الطالب",
    "teacher.students.deleteFailed": "فشل الحذف",
    "teacher.students.passwordReset": "تم إعادة تعيين كلمة المرور",
    "teacher.students.subtitle": "أدر طلابك.",
    "teacher.students.importPdf": "استيراد PDF",
    "teacher.students.noStudents": "لا يوجد طلاب بعد.",
    "teacher.students.addStudentTitle": "إضافة طالب",
    "teacher.students.firstName": "الاسم الأول",
    "teacher.students.lastName": "اسم العائلة",
    "teacher.students.serialNumber": "رقم التسجيل",
    "teacher.students.noSection": "بدون قسم",
    "teacher.students.emailPasswordInfo": "سيتم إنشاء بريد إلكتروني وكلمة مرور. شاركهما مع الطالب لتسجيل الدخول.",
    "teacher.students.credentialsTitle": "بيانات اعتماد الطالب",
    "director.exams.overview": "نظرة عامة على جميع الامتحانات حسب الأقسام.",
    "director.exams.allSections": "كل الأقسام",
    "director.exams.total": "المجموع",
    "director.exams.graded": "مُصحّح",
    "director.exams.pending": "قيد الانتظار",
    "director.exams.noExamsInSection": "لا توجد امتحانات في هذا القسم.",
    "director.exams.noExams": "لا توجد امتحانات بعد.",
    "director.exams.deleteConfirm": "هل تريد حذف الامتحان «{name}»؟ لا يمكن التراجع.",
    "director.exams.deleteSuccess": "تم حذف الامتحان",
    "director.exams.deleteFailed": "فشل الحذف",
    "director.exams.editTitle": "تعديل الامتحان",
    "director.exams.updateSuccess": "تم تحديث الامتحان",
    "director.exams.updateFailed": "فشل التحديث",
    "director.payment.fillAllFields": "يرجى ملء جميع حقول البطاقة",
    "director.payment.failed": "فشل الدفع",
    "director.payment.freeTrial": "تجربة مجانية",
    "director.payment.active": "نشط",
    "director.payment.card": "بطاقة",
    "director.analytics.loadFailed": "فشل تحميل التحليلات",
    "director.analytics.noDataAvailable": "لا تتوفر بيانات",
    "director.analytics.retry": "إعادة المحاولة",
    "director.teachers.couldNotCopy": "تعذر النسخ",
    "director.teachers.addSuccess": "تمت إضافة المعلم. شارك بيانات الدخول أدناه.",
    "director.teachers.addFailed": "فشل",
    "director.teachers.deleteConfirm": "هل تريد حذف المعلم {name}؟ لا يمكن التراجع عن هذا الإجراء.",
    "director.teachers.deleteSuccess": "تم حذف المعلم",
    "director.teachers.deleteFailed": "فشل الحذف",
    "director.teachers.subtitle": "أضف المعلمين وشارك بيانات الدخول المولّدة تلقائياً.",
    "director.teachers.addTeacherBtn": "إضافة معلم",
    "director.teachers.noTeachers": "لا يوجد معلمون بعد. اضغط «إضافة معلم» للبدء.",
    "director.teachers.name": "الاسم",
    "director.teachers.subject": "المادة",
    "director.teachers.email": "البريد الإلكتروني",
    "director.teachers.password": "كلمة المرور",
    "director.teachers.students": "الطلاب",
    "director.teachers.actions": "الإجراءات",
    "director.teachers.modalTitleAdd": "إضافة معلم",
    "director.teachers.modalTitleAdded": "تمت إضافة المعلم",
    "director.teachers.credentialsNote": "تمت الإضافة. شارك بيانات الدخول هذه مع المعلم — لن تظهر مرة أخرى.",
    "director.teachers.done": "تم",
    "director.teachers.firstName": "الاسم الأول",
    "director.teachers.lastName": "اسم العائلة",
    "director.teachers.subjectLabel": "المادة",
    "director.teachers.autoGenerate": "سيتم إنشاء بريد إلكتروني فريد وكلمة مرور من 10 أحرف تلقائياً لهذا المعلم.",
    "director.students.subtitle": "جميع الطلاب من جميع المعلمين.",
    "director.students.noStudents": "لا يوجد طلاب بعد.",
    "director.students.unassigned": "غير معيّن",
    "director.students.grades": "درجات",
    "director.students.present": "حاضر",
    "director.students.absent": "غائب",
    "director.students.notes": "ملاحظات",
    "director.students.password": "كلمة المرور:",
    "director.students.viewDetails": "عرض التفاصيل",
    "director.students.student": "طالب",
    "director.students.avg": "المعدل",
    "director.students.presentLabel": "حاضر",
    "director.students.absentLabel": "غائب",
    "director.students.notesLabel": "ملاحظات",
    "director.students.gradesTitle": "الدرجات",
    "director.students.behaviorTitle": "ملاحظات السلوك",
    "director.students.nothingHere": "لا شيء هنا بعد.",
    "director.messages.chooseRecipient": "يرجى اختيار مستلم",
    "director.messages.sent": "تم إرسال الرسالة",
    "director.messages.sendFailed": "فشل الإرسال",
    "director.notifications.loadFailed": "فشل تحميل الإشعارات",
    "director.notifications.unreadCount": "{count} غير مقروءة",
    "director.notifications.retry": "إعادة المحاولة",
    "student.overview.welcome": "مرحباً، {name} 👋",
    "student.overview.dashboardSubtitle": "لوحة تحكمك كطالب",
    "student.overview.overallAvg": "المعدل العام",
    "student.overview.present": "حاضر",
    "student.overview.grades": "الدرجات",
    "student.overview.notes": "ملاحظات",
    "student.overview.recentGrades": "الدرجات الأخيرة",
    "student.overview.noGrades": "لا توجد درجات بعد.",
    "student.overview.behaviorNotes": "ملاحظات السلوك",
    "student.overview.noBehaviorNotes": "لا توجد ملاحظات سلوك بعد.",
    "student.overview.recentMessages": "الرسائل الأخيرة",
    "student.overview.from": "من",
    "student.overview.retry": "إعادة المحاولة",
    "student.reportCard.retry": "إعادة المحاولة",
    "student.reportCard.title": "كشف النقط",
    "student.reportCard.subtitle": "ملخص الأداء الأكاديمي",
    "student.reportCard.downloadPdf": "تحميل PDF",
    "student.reportCard.emptyState": "لم يتم تسجيل أي درجات بعد. سيكون كشف النقط متاحاً بعد إدخال الدرجات.",
    "student.reportCard.student": "طالب",
    "student.reportCard.teacher": "المعلم:",
    "student.reportCard.overallAverage": "المعدل العام",
    "student.reportCard.periodAverage": "معدل الفترة",
    "student.reportCard.subject": "المادة",
    "student.reportCard.score": "النقطة",
    "student.reportCard.grade": "التقدير",
    "student.reportCard.excellent": "ممتاز",
    "student.reportCard.passing": "مقبول",
    "student.reportCard.needsImprovement": "يحتاج تحسين",
    "student.reportCard.weightedAverage": "المعدل الموزون:",
    "student.reportCard.examCount": "امتحان(ات)",
    "student.homework.submitted": "تم التسليم",
    "student.homework.failed": "فشل",
    "student.homework.subtitle": "عرض وتسليم واجباتك.",
    "student.homework.noHomework": "لم يتم تعيين أي واجبات بعد.",
    "student.homework.teacher": "المعلم:",
    "student.homework.due": "التسليم:",
    "student.homework.section": "القسم:",
    "student.homework.attachment": "مرفق",
    "student.homework.submit": "تسليم",
    "student.homework.feedback": "التعليق",
    "student.homework.graded": "تم التصحيح",
    "student.homework.submittedWaiting": "تم التسليم — بانتظار التصحيح.",
    "student.homework.submitHomework": "تسليم الواجب",
    "student.homework.yourAnswer": "إجابتك",
    "student.homework.answerPlaceholder": "اكتب إجابتك هنا...",
    "student.homework.fileUrlOptional": "رابط الملف (اختياري)",
    "student.homework.cancel": "إلغاء",
    "student.homework.overdue": "متأخر",
    "student.homework.pending": "قيد الانتظار",
    "student.exams.retry": "إعادة المحاولة",
    "student.exams.title": "الامتحانات",
    "student.exams.subtitle": "نتائج ودرجات امتحاناتك.",
    "student.exams.noExams": "لا توجد امتحانات بعد.",
    "student.exams.pending": "قيد الانتظار",
    "student.exams.graded": "مُصحّح",
    "student.grades.retry": "إعادة المحاولة",
    "student.grades.title": "درجاتي",
    "student.grades.subtitle": "جميع درجاتك ومعدلاتك.",
    "student.grades.overallAverage": "المعدل العام",
    "student.grades.noGrades": "لا توجد درجات بعد.",
    "student.grades.average": "المعدل",
    "student.grades.noGradesPeriod": "لا توجد درجات في هذه الفترة.",
    "student.attendance.retry": "إعادة المحاولة",
    "student.attendance.title": "حضوري",
    "student.attendance.subtitle": "سجل حضورك.",
    "student.attendance.present": "حاضر",
    "student.attendance.absent": "غائب",
    "student.attendance.noRecords": "لا توجد سجلات حضور بعد.",
    "student.behavior.retry": "إعادة المحاولة",
    "student.behavior.title": "ملاحظات السلوك",
    "student.behavior.subtitle": "ملاحظات من معلميك.",
    "student.behavior.noNotes": "لا توجد ملاحظات سلوك بعد. واصل العمل الجيد!",
    "student.messages.sent": "تم إرسال الرسالة لمعلميك",
    "student.messages.sendFailed": "فشل الإرسال",
    "student.messages.title": "الرسائل",
    "student.messages.subtitle": "تحدث مع معلميك والمدير.",
    "student.messages.newMessage": "رسالة جديدة",
    "student.messages.to": "إلى",
    "student.messages.allTeachers": "كل معلميك",
    "student.messages.message": "الرسالة",
    "student.messages.placeholder": "اكتب رسالتك…",
    "student.messages.send": "إرسال",
    "student.messages.conversation": "المحادثة",
    "student.messages.retry": "إعادة المحاولة",
    "student.messages.noMessages": "لا توجد رسائل بعد",
    "student.messages.you": "أنت",
    "student.lessons.retry": "إعادة المحاولة",
    "student.lessons.title": "الدروس",
    "student.lessons.subtitle": "تصفح دروس قسمك.",
    "student.lessons.noLessons": "لا توجد دروس متاحة بعد.",
    "student.lessons.noContent": "لا يوجد محتوى.",
    "student.lessons.file": "ملف",
    "student.lessons.video": "فيديو",
  }
};

const LanguageContext = createContext<LanguageContextType | null>(null);

function getSavedLocale(): Locale {
  if (typeof window === "undefined") return "fr";
  try {
    const saved = localStorage.getItem("locale");
    if (saved && ["en", "fr", "ar"].includes(saved)) return saved as Locale;
  } catch {}
  return "fr";
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("fr");
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    const saved = getSavedLocale();
    setLocaleState(saved);
    document.documentElement.setAttribute("dir", saved === "ar" ? "rtl" : "ltr");
    document.documentElement.setAttribute("lang", saved);
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (!hydrated) return;
    const dir = locale === "ar" ? "rtl" : "ltr";
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", locale);
  }, [locale, hydrated]);

  const setLocale = (l: Locale) => {
    setLocaleState(l);
    try {
      localStorage.setItem("locale", l);
    } catch {}
    const dir = l === "ar" ? "rtl" : "ltr";
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", l);
  };

  const dir = locale === "ar" ? "rtl" : "ltr";
  const t = (key: string, vars?: Record<string, string | number>) => {
    let str = translations[locale]?.[key] ?? translations.fr[key] ?? key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ locale, setLocale, dir, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
